# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Build

  jobs:
  - job: Build
    pool: sonic-image-builder

    steps:
    - script: |
        scripts/unpack_lfs.sh
        make JOBS=4 DEBIAN_BUILD=1 DEBIAN_CUSTOMER=1 buster
      displayName: "Make"
