# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master

resources:
  repositories:
    - repository: Cisco-8000-sonic-sdk
      type: github
      name: Cisco-8000-sonic/sdk
      ref: main
      endpoint: cisco

stages:
- stage: Build

  jobs:
  - job: Build
    timeoutInMinutes: 1200
    pool: sonicbld_16c

    steps:
    - checkout: self
      displayName: Checkout self

    - checkout: Cisco-8000-sonic-sdk
      path: sdk
      submodules: true
      persistCredentials: true

    - script: |
        ls -l .
        ls -l ..
      displayName: "List files"
