# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master

stages:
- stage: Build

  jobs:
  - job: Build
    timeoutInMinutes: 1200
    pool: sonicbld_16c

    steps:
    - script: |
        sudo pip install PyYAML
      displayName: "Install packages"

    - script: |
        scripts/unpack_lfs.sh
        make JOBS=16 DEBIAN_BUILD=1 DEBIAN_CUSTOMER=1 buster
      displayName: "Build packages"

    - publish: $(System.DefaultWorkingDirectory)/target
      artifact: 'cisco-8000-sonic.sdk'
      displayName: "Archive the sdk"
