//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
//                        ESILICON CORPORATION CONFIDENTIAL                           //
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
//      COPYRIGHT (C) 2000-2019 ESILICON CORPORATION. ALL RIGHTS RESERVED.            //
//      NO PART OF THIS DOCUMENT MAY BE PHOTOCOPIED, REPRODUCED OR TRANSLATED         //
//      TO ANOTHER PROGRAM LANGUAGE WITHOUT THE PRIOR WRITTEN CONSENT OF ESILICON     //
//      CORPORATION. THIS DATA CAN ONLY BE USED AS AUTHORIZED BY A LICENSE            //
//      FROM ESILICON CORPORATION. IN ADDITION, THIS DATA IS PROTECTED BY             //
//      COPYRIGHT LAW AND INTERNATIONAL TREATIES.                                     //
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
//                                                                                    //
// Revision           : 1.2                                                           //
// Generation date    : May 17 2019                                                   //
//                                                                                    //
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
//                                                                                    //
// View type          : C Code                                                        //
// Instance name      : ts_7ff_hbm2llhbmphy                                           //
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
//                                                                                    //
// Verified with:                                                                     //
//    a. Synopsys | VCS | N-2017.12-SP1                                               //
//                                                                                    //
// Assumptions:                                                                       //
//    a. Compiler: gcc - GNU project C and C++ compiler                               //
//                                                                                    //
// Limitations:                                                                       //
//    a. Do not support timing backannotation                                         //
//                                                                                    //
// Known bugs         : None.                                                         //
//                                                                                    //
// Known work arounds : N/A                                                           //
//                                                                                    //
// Comments           : None.                                                         //
//                                                                                    //
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
// REVISION HISTORY                                                                   //
// Revision      Date           Author        Description                             //
// -----------------------------------------------------------------------------------//
//  1.2       May 17 2019       knerurkar     No change                               //
//  1.1       Mar 08 2019       knerurkar     No change                               //
//  1.0       Feb 19 2019       knerurkar     First official release                  //
// -----------------------------------------------------------------------------------//  


//Address define for IEEE500
//IEEE
#define ESI_IEEE_BYPASS                      0x00
#define ESI_IEEE_EXTEST_TX                   0x01  //tx of PHY, rx of dram
#define ESI_IEEE_EXTEST_RX                   0x02  //rx of phy, tx of dram
#define ESI_IEEE_IO_CFG                      0x03
#define ESI_IEEE_DLL_CFG                     0x04
#define ESI_IEEE_RESET_CONTROL               0x05
#define ESI_IEEE_SLAVE_DLL_BIST              0x06
#define ESI_IEEE_MASTER_DLL_BIST             0x07
#define ESI_IEEE_ZQ_CFG                      0x08
#define ESI_IEEE_GLOBAL_CONFIG               0x09
#define ESI_IEEE_READ_FIFO_RESET_CFG         0x0A
#define ESI_IEEE_READ_DELAY_CFG              0x0B
#define ESI_IEEE_PARITY_REPAIR_MODE_CFG      0x0C
#define ESI_IEEE_MIDSTACK_LOOPBACK           0x0D
#define ESI_IEEE_MRS_CFG                     0x0E

#define ESI_IEEE_CLK_DISABLE_CFG             0x10
#define ESI_IEEE_AW_MANUAL_CFG               0x11
#define ESI_IEEE_REPAIR_CFG                  0x12
#define ESI_IEEE_MISR_LOOPBACK               0x13
#define ESI_IEEE_DW0_DATA_PATTERN            0x14
#define ESI_IEEE_DW1_DATA_PATTERN            0x15
#define ESI_IEEE_DW2_DATA_PATTERN            0x16
#define ESI_IEEE_DW3_DATA_PATTERN            0x17
#define ESI_IEEE_AW_DATA_PATTERN             0x18
#define ESI_IEEE_ERROR_PATTERN_DBG           0x19
#define ESI_IEEE_FIFO_DBG                    0x1A
#define ESI_IEEE_CMD_CNT_DBG                 0x1B
#define ESI_IEEE_PLL_CAP                     0x1E
#define ESI_IEEE_PLL_CFG                     0x1F

//configuration for training

#define ESI_IEEE_TRAINING_ENAB               0x20
#define ESI_IEEE_TRAINING_GO                 0x21
#define ESI_IEEE_TRAINING_DONE               0x22


//Address define for APB
//APB
#define ESI_PLL_CFG_0                         0x000
#define ESI_PLL_CFG_1                         0x001
#define ESI_PLL_LOCKED                        0x002
#define ESI_PLL_CAP                           0x003
#define ESI_ZQCAL_CFG                         0x010
#define ESI_ZQCAL_STS                         0x011
#define ESI_PHY_CONTROL_PARITY_LATENCY        0x014
#define ESI_REPAIR_MODE_DW                    0x01F

#define ESI_DRIVE_STRENGTH_CFG                0x040
#define ESI_DLL_CFG_MASTER                    0x041 
#define ESI_DLL_STS_MASTER                    0x042
#define ESI_IO_CFG_MIDSTACK                   0x043
#define ESI_MONITOR_SEL                       0x044

#define ESI_HBM_RESET_CONTROL                 0x080

#define ESI_MISR_AW_START                     0x100
#define ESI_MISR_DW_START                     0x101
#define ESI_LOOPBACK_START                    0x102

#define ESI_LOOPBACK_ENAB_A                   0x104
#define ESI_LOOPBACK_ENAB_B                   0x124
#define ESI_LOOPBACK_ENAB_C                   0x144
#define ESI_LOOPBACK_ENAB_D                   0x164
#define ESI_LOOPBACK_ENAB_E                   0x184
#define ESI_LOOPBACK_ENAB_F                   0x1A4
#define ESI_LOOPBACK_ENAB_G                   0x1C4
#define ESI_LOOPBACK_ENAB_H                   0x1E4

#define ESI_APB_PREFIX_MSLB                   0x3
#define ESI_MSLB_CFG                          0x300
#define ESI_MSLB_RUNTIME_0                    0x301
#define ESI_MSLB_RUNTIME_1                    0x302
#define ESI_MSLB_SEED_GEN                     0x303
#define ESI_MSLB_CUSPAT_GEN_CYC0              0x304
#define ESI_MSLB_CUSPAT_GEN_CYC1              0x305
#define ESI_MSLB_CUSPAT_GEN_CYC2              0x306
#define ESI_MSLB_CUSPAT_GEN_CYC3              0x307
#define ESI_MSLB_CUSPAT_GEN_CYC4              0x308
#define ESI_MSLB_CUSPAT_GEN_CYC5              0x309
#define ESI_MSLB_CUSPAT_GEN_CYC6              0x30A
#define ESI_MSLB_CUSPAT_GEN_CYC7              0x30B
#define ESI_MSLB_SEED_CHK                     0x30C
#define ESI_MSLB_CUSPAT_CHK_CYC0              0x30D
#define ESI_MSLB_CUSPAT_CHK_CYC1              0x30E
#define ESI_MSLB_CUSPAT_CHK_CYC2              0x30F
#define ESI_MSLB_CUSPAT_CHK_CYC3              0x310
#define ESI_MSLB_CUSPAT_CHK_CYC4              0x311
#define ESI_MSLB_CUSPAT_CHK_CYC5              0x312
#define ESI_MSLB_CUSPAT_CHK_CYC6              0x313
#define ESI_MSLB_CUSPAT_CHK_CYC7              0x314
#define ESI_MSLB_ERR_INJ                      0x315
#define ESI_MSLB_MASK                         0x316
#define ESI_MSLB_START                        0x317
#define ESI_MSLB_STS                          0x318
#define ESI_MSLB_STICKY                       0x319
#define ESI_MSLB_ERR_PATTERN                  0x31A


#define ESI_APB_PREFIX_MRS                    0x5
#define ESI_MRS0_CFG_A                       0x500
#define ESI_MRS0_CFG_B                       0x520
#define ESI_MRS0_CFG_C                       0x540
#define ESI_MRS0_CFG_D                       0x560
#define ESI_MRS0_CFG_E                       0x580
#define ESI_MRS0_CFG_F                       0x5A0
#define ESI_MRS0_CFG_G                       0x5C0
#define ESI_MRS0_CFG_H                       0x5E0
#define ESI_MRS1_CFG_A                       0x501
#define ESI_MRS1_CFG_B                       0x521
#define ESI_MRS1_CFG_C                       0x541
#define ESI_MRS1_CFG_D                       0x561
#define ESI_MRS1_CFG_E                       0x581
#define ESI_MRS1_CFG_F                       0x5A1
#define ESI_MRS1_CFG_G                       0x5C1
#define ESI_MRS1_CFG_H                       0x5E1
#define ESI_MRS2_CFG_A                       0x502
#define ESI_MRS2_CFG_B                       0x522
#define ESI_MRS2_CFG_C                       0x542
#define ESI_MRS2_CFG_D                       0x562
#define ESI_MRS2_CFG_E                       0x582
#define ESI_MRS2_CFG_F                       0x5A2
#define ESI_MRS2_CFG_G                       0x5C2
#define ESI_MRS2_CFG_H                       0x5E2
#define ESI_MRS3_CFG_A                       0x503
#define ESI_MRS3_CFG_B                       0x523
#define ESI_MRS3_CFG_C                       0x543
#define ESI_MRS3_CFG_D                       0x563
#define ESI_MRS3_CFG_E                       0x583
#define ESI_MRS3_CFG_F                       0x5A3
#define ESI_MRS3_CFG_G                       0x5C3
#define ESI_MRS3_CFG_H                       0x5E3
#define ESI_MRS4_CFG_A                       0x504
#define ESI_MRS4_CFG_B                       0x524
#define ESI_MRS4_CFG_C                       0x544
#define ESI_MRS4_CFG_D                       0x564
#define ESI_MRS4_CFG_E                       0x584
#define ESI_MRS4_CFG_F                       0x5A4
#define ESI_MRS4_CFG_G                       0x5C4
#define ESI_MRS4_CFG_H                       0x5E4
#define ESI_MRS5_CFG_A                       0x505
#define ESI_MRS5_CFG_B                       0x525
#define ESI_MRS5_CFG_C                       0x545
#define ESI_MRS5_CFG_D                       0x565
#define ESI_MRS5_CFG_E                       0x585
#define ESI_MRS5_CFG_F                       0x5A5
#define ESI_MRS5_CFG_G                       0x5C5
#define ESI_MRS5_CFG_H                       0x5E5
#define ESI_MRS6_CFG_A                       0x506
#define ESI_MRS6_CFG_B                       0x526
#define ESI_MRS6_CFG_C                       0x546
#define ESI_MRS6_CFG_D                       0x566
#define ESI_MRS6_CFG_E                       0x586
#define ESI_MRS6_CFG_F                       0x5A6
#define ESI_MRS6_CFG_G                       0x5C6
#define ESI_MRS6_CFG_H                       0x5E6
#define ESI_MRS7_CFG_A                       0x507
#define ESI_MRS7_CFG_B                       0x527
#define ESI_MRS7_CFG_C                       0x547
#define ESI_MRS7_CFG_D                       0x567
#define ESI_MRS7_CFG_E                       0x587
#define ESI_MRS7_CFG_F                       0x5A7
#define ESI_MRS7_CFG_G                       0x5C7
#define ESI_MRS7_CFG_H                       0x5E7

#define ESI_TRAINING_PREFIX_FSM_CFG        0x6
#define ESI_TRAINING_MINRANGE_CK           0x00
#define ESI_TRAINING_MINRANGE_CK_A         0x600
#define ESI_TRAINING_MINRANGE_CK_B         0x620
#define ESI_TRAINING_MINRANGE_CK_C         0x640
#define ESI_TRAINING_MINRANGE_CK_D         0x660
#define ESI_TRAINING_MINRANGE_CK_E         0x680
#define ESI_TRAINING_MINRANGE_CK_F         0x6A0
#define ESI_TRAINING_MINRANGE_CK_G         0x6C0
#define ESI_TRAINING_MINRANGE_CK_H         0x6E0

#define ESI_TRAINING_MINRANGE_WDQS         0x01
#define ESI_TRAINING_MINRANGE_WDQS_A       0x601
#define ESI_TRAINING_MINRANGE_WDQS_B       0x621
#define ESI_TRAINING_MINRANGE_WDQS_C       0x641
#define ESI_TRAINING_MINRANGE_WDQS_D       0x661
#define ESI_TRAINING_MINRANGE_WDQS_E       0x681
#define ESI_TRAINING_MINRANGE_WDQS_F       0x6A1
#define ESI_TRAINING_MINRANGE_WDQS_G       0x6C1
#define ESI_TRAINING_MINRANGE_WDQS_H       0x6E1

#define ESI_TRAINING_MINRANGE_RDQS         0x02
#define ESI_TRAINING_MINRANGE_RDQS_A       0x602
#define ESI_TRAINING_MINRANGE_RDQS_B       0x622
#define ESI_TRAINING_MINRANGE_RDQS_C       0x642
#define ESI_TRAINING_MINRANGE_RDQS_D       0x662
#define ESI_TRAINING_MINRANGE_RDQS_E       0x682
#define ESI_TRAINING_MINRANGE_RDQS_F       0x6A2
#define ESI_TRAINING_MINRANGE_RDQS_G       0x6C2
#define ESI_TRAINING_MINRANGE_RDQS_H       0x6E2

#define ESI_TRAINING_MINRANGE_RDSEL        0x03
#define ESI_TRAINING_MINRANGE_RDSEL_A      0x603
#define ESI_TRAINING_MINRANGE_RDSEL_B      0x623
#define ESI_TRAINING_MINRANGE_RDSEL_C      0x643
#define ESI_TRAINING_MINRANGE_RDSEL_D      0x663
#define ESI_TRAINING_MINRANGE_RDSEL_E      0x683
#define ESI_TRAINING_MINRANGE_RDSEL_F      0x6A3
#define ESI_TRAINING_MINRANGE_RDSEL_G      0x6C3
#define ESI_TRAINING_MINRANGE_RDSEL_H      0x6E3

#define ESI_TRAINING_CK_FIRST_OK           0x04
#define ESI_TRAINING_CK_FIRST_OK_A         0x604
#define ESI_TRAINING_CK_FIRST_OK_B         0x624
#define ESI_TRAINING_CK_FIRST_OK_C         0x644
#define ESI_TRAINING_CK_FIRST_OK_D         0x664
#define ESI_TRAINING_CK_FIRST_OK_E         0x684
#define ESI_TRAINING_CK_FIRST_OK_F         0x6A4
#define ESI_TRAINING_CK_FIRST_OK_G         0x6C4
#define ESI_TRAINING_CK_FIRST_OK_H         0x6E4

#define ESI_TRAINING_WDQS0_FIRST_OK          0x05
#define ESI_TRAINING_WDQS0_FIRST_OK_A      0x605
#define ESI_TRAINING_WDQS0_FIRST_OK_B      0x625
#define ESI_TRAINING_WDQS0_FIRST_OK_C      0x645
#define ESI_TRAINING_WDQS0_FIRST_OK_D      0x665
#define ESI_TRAINING_WDQS0_FIRST_OK_E      0x685
#define ESI_TRAINING_WDQS0_FIRST_OK_F      0x6A5
#define ESI_TRAINING_WDQS0_FIRST_OK_G      0x6C5
#define ESI_TRAINING_WDQS0_FIRST_OK_H      0x6E5
#define ESI_TRAINING_WDQS1_FIRST_OK          0x06
#define ESI_TRAINING_WDQS1_FIRST_OK_A      0x606
#define ESI_TRAINING_WDQS1_FIRST_OK_B      0x626
#define ESI_TRAINING_WDQS1_FIRST_OK_C      0x646
#define ESI_TRAINING_WDQS1_FIRST_OK_D      0x666
#define ESI_TRAINING_WDQS1_FIRST_OK_E      0x686
#define ESI_TRAINING_WDQS1_FIRST_OK_F      0x6A6
#define ESI_TRAINING_WDQS1_FIRST_OK_G      0x6C6
#define ESI_TRAINING_WDQS1_FIRST_OK_H      0x6E6
#define ESI_TRAINING_WDQS2_FIRST_OK          0x07
#define ESI_TRAINING_WDQS2_FIRST_OK_A      0x607
#define ESI_TRAINING_WDQS2_FIRST_OK_B      0x627
#define ESI_TRAINING_WDQS2_FIRST_OK_C      0x647
#define ESI_TRAINING_WDQS2_FIRST_OK_D      0x667
#define ESI_TRAINING_WDQS2_FIRST_OK_E      0x687
#define ESI_TRAINING_WDQS2_FIRST_OK_F      0x6A7
#define ESI_TRAINING_WDQS2_FIRST_OK_G      0x6C7
#define ESI_TRAINING_WDQS2_FIRST_OK_H      0x6E7
#define ESI_TRAINING_WDQS3_FIRST_OK          0x08
#define ESI_TRAINING_WDQS3_FIRST_OK_A      0x608
#define ESI_TRAINING_WDQS3_FIRST_OK_B      0x628
#define ESI_TRAINING_WDQS3_FIRST_OK_C      0x648
#define ESI_TRAINING_WDQS3_FIRST_OK_D      0x668
#define ESI_TRAINING_WDQS3_FIRST_OK_E      0x688
#define ESI_TRAINING_WDQS3_FIRST_OK_F      0x6A8
#define ESI_TRAINING_WDQS3_FIRST_OK_G      0x6C8
#define ESI_TRAINING_WDQS3_FIRST_OK_H      0x6E8
#define ESI_TRAINING_RDQS0_FIRST_OK          0x09
#define ESI_TRAINING_RDQS0_FIRST_OK_A      0x609
#define ESI_TRAINING_RDQS0_FIRST_OK_B      0x629
#define ESI_TRAINING_RDQS0_FIRST_OK_C      0x649
#define ESI_TRAINING_RDQS0_FIRST_OK_D      0x669
#define ESI_TRAINING_RDQS0_FIRST_OK_E      0x689
#define ESI_TRAINING_RDQS0_FIRST_OK_F      0x6A9
#define ESI_TRAINING_RDQS0_FIRST_OK_G      0x6C9
#define ESI_TRAINING_RDQS0_FIRST_OK_H      0x6E9
#define ESI_TRAINING_RDQS1_FIRST_OK          0x0A
#define ESI_TRAINING_RDQS1_FIRST_OK_A      0x60A
#define ESI_TRAINING_RDQS1_FIRST_OK_B      0x62A
#define ESI_TRAINING_RDQS1_FIRST_OK_C      0x64A
#define ESI_TRAINING_RDQS1_FIRST_OK_D      0x66A
#define ESI_TRAINING_RDQS1_FIRST_OK_E      0x68A
#define ESI_TRAINING_RDQS1_FIRST_OK_F      0x6AA
#define ESI_TRAINING_RDQS1_FIRST_OK_G      0x6CA
#define ESI_TRAINING_RDQS1_FIRST_OK_H      0x6EA
#define ESI_TRAINING_RDQS2_FIRST_OK          0x0B
#define ESI_TRAINING_RDQS2_FIRST_OK_A      0x60B
#define ESI_TRAINING_RDQS2_FIRST_OK_B      0x62B
#define ESI_TRAINING_RDQS2_FIRST_OK_C      0x64B
#define ESI_TRAINING_RDQS2_FIRST_OK_D      0x66B
#define ESI_TRAINING_RDQS2_FIRST_OK_E      0x68B
#define ESI_TRAINING_RDQS2_FIRST_OK_F      0x6AB
#define ESI_TRAINING_RDQS2_FIRST_OK_G      0x6CB
#define ESI_TRAINING_RDQS2_FIRST_OK_H      0x6EB
#define ESI_TRAINING_RDQS3_FIRST_OK          0x0D
#define ESI_TRAINING_RDQS3_FIRST_OK_A      0x60D
#define ESI_TRAINING_RDQS3_FIRST_OK_B      0x62D
#define ESI_TRAINING_RDQS3_FIRST_OK_C      0x64D
#define ESI_TRAINING_RDQS3_FIRST_OK_D      0x66D
#define ESI_TRAINING_RDQS3_FIRST_OK_E      0x68D
#define ESI_TRAINING_RDQS3_FIRST_OK_F      0x6AD
#define ESI_TRAINING_RDQS3_FIRST_OK_G      0x6CD
#define ESI_TRAINING_RDQS3_FIRST_OK_H      0x6ED

#define ESI_TRAINING_PREFIX_CFG        0x7
#define ESI_TRAINING_GO                    0x700
#define ESI_TRAINING_DONE                  0x701
#define ESI_TRAINING_OK                    0x702
#define ESI_TRAINING_TYPE                  0x703
#define ESI_TRAINING_CHANNEL_ENAB          0x704
#define ESI_TRAINING_DLL_RANGE             0x705
#define ESI_TRAINING_RDSEL_RANGE           0x706
#define ESI_TRAINING_CORR_CK               0x707 
#define ESI_TRAINING_CORR_WDQS             0x708 
#define ESI_TRAINING_CORR_RDQS             0x709 
#define ESI_TRAINING_CORR_RDSEL            0x70A 
#define ESI_TRAINING_CK_ERROR              0x70B
#define ESI_TRAINING_WDQS_ERROR            0x70C
#define ESI_TRAINING_RDQS_ERROR            0x70D
#define ESI_TRAINING_RDSEL_ERROR           0x70E

#define ESI_TRAINING_DOREPAIR              0x70F 

#define ESI_TRAINING_MISR_CHANNEL          0x710 
#define ESI_TRAINING_MISR_GO               0x711 
#define ESI_TRAINING_MISR_DONE             0x712 
#define ESI_TRAINING_MISR_OP               0x713 
#define ESI_TRAINING_ENB_TEST_CTRL         0x714 
#define ESI_TRAINING_STICKY_CKE            0x715 
#define ESI_TRAINING_STICKY_COL            0x716 
#define ESI_TRAINING_STICKY_ROW            0x717 
#define ESI_TRAINING_STICKY_DW0_BYTE0      0x718 
#define ESI_TRAINING_STICKY_DW0_BYTE1      0x719 
#define ESI_TRAINING_STICKY_DW0_BYTE2      0x71A 
#define ESI_TRAINING_STICKY_DW0_BYTE3      0x71B 
#define ESI_TRAINING_STICKY_DW1_BYTE0      0x71C 
#define ESI_TRAINING_STICKY_DW1_BYTE1      0x71D 
#define ESI_TRAINING_STICKY_DW1_BYTE2      0x71E 
#define ESI_TRAINING_STICKY_DW1_BYTE3      0x71F 
#define ESI_TRAINING_STICKY_DW2_BYTE0      0x720 
#define ESI_TRAINING_STICKY_DW2_BYTE1      0x721 
#define ESI_TRAINING_STICKY_DW2_BYTE2      0x722 
#define ESI_TRAINING_STICKY_DW2_BYTE3      0x723 
#define ESI_TRAINING_STICKY_DW3_BYTE0      0x724 
#define ESI_TRAINING_STICKY_DW3_BYTE1      0x725 
#define ESI_TRAINING_STICKY_DW3_BYTE2      0x726 
#define ESI_TRAINING_STICKY_DW3_BYTE3      0x727 

#define ESI_DRAM_REPAIR_COL                0x7F0 
#define ESI_DRAM_REPAIR_ROW                0x7F1 
#define ESI_DRAM_REPAIR_DW0                0x7F2 
#define ESI_DRAM_REPAIR_DW1                0x7F3 
#define ESI_DRAM_REPAIR_DW2                0x7F4 
#define ESI_DRAM_REPAIR_DW3                0x7F5 


// channel
#define ESI_TRAINING_PREFIX_DLL_CFG            0x8
#define ESI_TRAINING_DLL_CFG_CK               0x00
#define ESI_TRAINING_DLL_CFG_WDQS0            0x01
#define ESI_TRAINING_DLL_CFG_WDQS1            0x02
#define ESI_TRAINING_DLL_CFG_WDQS2            0x03
#define ESI_TRAINING_DLL_CFG_WDQS3            0x04
#define ESI_TRAINING_DLL_CFG_RDQS0            0x05
#define ESI_TRAINING_DLL_CFG_RDQS1            0x06
#define ESI_TRAINING_DLL_CFG_RDQS2            0x07
#define ESI_TRAINING_DLL_CFG_RDQS3            0x08
#define ESI_DLL_CFG_SLAVE_AW_A                 0x800
#define ESI_DLL_CFG_SLAVE_AW_B                 0x820
#define ESI_DLL_CFG_SLAVE_AW_C                 0x840
#define ESI_DLL_CFG_SLAVE_AW_D                 0x860
#define ESI_DLL_CFG_SLAVE_AW_E                 0x880
#define ESI_DLL_CFG_SLAVE_AW_F                 0x8A0
#define ESI_DLL_CFG_SLAVE_AW_G                 0x8C0
#define ESI_DLL_CFG_SLAVE_AW_H                 0x8E0
#define ESI_DLL_CFG_SLAVE_WDQS_DW0_A           0x801
#define ESI_DLL_CFG_SLAVE_WDQS_DW1_A           0x802
#define ESI_DLL_CFG_SLAVE_WDQS_DW2_A           0x803
#define ESI_DLL_CFG_SLAVE_WDQS_DW3_A           0x804
#define ESI_DLL_CFG_SLAVE_WDQS_DW0_B           0x821
#define ESI_DLL_CFG_SLAVE_WDQS_DW1_B           0x822
#define ESI_DLL_CFG_SLAVE_WDQS_DW2_B           0x823
#define ESI_DLL_CFG_SLAVE_WDQS_DW3_B           0x824
#define ESI_DLL_CFG_SLAVE_WDQS_DW0_C           0x841
#define ESI_DLL_CFG_SLAVE_WDQS_DW1_C           0x842
#define ESI_DLL_CFG_SLAVE_WDQS_DW2_C           0x843
#define ESI_DLL_CFG_SLAVE_WDQS_DW3_C           0x844
#define ESI_DLL_CFG_SLAVE_WDQS_DW0_D           0x861
#define ESI_DLL_CFG_SLAVE_WDQS_DW1_D           0x862
#define ESI_DLL_CFG_SLAVE_WDQS_DW2_D           0x863
#define ESI_DLL_CFG_SLAVE_WDQS_DW3_D           0x864
#define ESI_DLL_CFG_SLAVE_WDQS_DW0_E           0x881
#define ESI_DLL_CFG_SLAVE_WDQS_DW1_E           0x882
#define ESI_DLL_CFG_SLAVE_WDQS_DW2_E           0x883
#define ESI_DLL_CFG_SLAVE_WDQS_DW3_E           0x884
#define ESI_DLL_CFG_SLAVE_WDQS_DW0_F           0x8A1
#define ESI_DLL_CFG_SLAVE_WDQS_DW1_F           0x8A2
#define ESI_DLL_CFG_SLAVE_WDQS_DW2_F           0x8A3
#define ESI_DLL_CFG_SLAVE_WDQS_DW3_F           0x8A4
#define ESI_DLL_CFG_SLAVE_WDQS_DW0_G           0x8C1
#define ESI_DLL_CFG_SLAVE_WDQS_DW1_G           0x8C2
#define ESI_DLL_CFG_SLAVE_WDQS_DW2_G           0x8C3
#define ESI_DLL_CFG_SLAVE_WDQS_DW3_G           0x8C4
#define ESI_DLL_CFG_SLAVE_WDQS_DW0_H           0x8E1
#define ESI_DLL_CFG_SLAVE_WDQS_DW1_H           0x8E2
#define ESI_DLL_CFG_SLAVE_WDQS_DW2_H           0x8E3
#define ESI_DLL_CFG_SLAVE_WDQS_DW3_H           0x8E4
#define ESI_DLL_CFG_SLAVE_RDQS_DW0_A           0x805
#define ESI_DLL_CFG_SLAVE_RDQS_DW1_A           0x806
#define ESI_DLL_CFG_SLAVE_RDQS_DW2_A           0x807
#define ESI_DLL_CFG_SLAVE_RDQS_DW3_A           0x808
#define ESI_DLL_CFG_SLAVE_RDQS_DW0_B           0x825
#define ESI_DLL_CFG_SLAVE_RDQS_DW1_B           0x826
#define ESI_DLL_CFG_SLAVE_RDQS_DW2_B           0x827
#define ESI_DLL_CFG_SLAVE_RDQS_DW3_B           0x828
#define ESI_DLL_CFG_SLAVE_RDQS_DW0_C           0x845
#define ESI_DLL_CFG_SLAVE_RDQS_DW1_C           0x846
#define ESI_DLL_CFG_SLAVE_RDQS_DW2_C           0x847
#define ESI_DLL_CFG_SLAVE_RDQS_DW3_C           0x848
#define ESI_DLL_CFG_SLAVE_RDQS_DW0_D           0x865
#define ESI_DLL_CFG_SLAVE_RDQS_DW1_D           0x866
#define ESI_DLL_CFG_SLAVE_RDQS_DW2_D           0x867
#define ESI_DLL_CFG_SLAVE_RDQS_DW3_D           0x868
#define ESI_DLL_CFG_SLAVE_RDQS_DW0_E           0x885
#define ESI_DLL_CFG_SLAVE_RDQS_DW1_E           0x886
#define ESI_DLL_CFG_SLAVE_RDQS_DW2_E           0x887
#define ESI_DLL_CFG_SLAVE_RDQS_DW3_E           0x888
#define ESI_DLL_CFG_SLAVE_RDQS_DW0_F           0x8A5
#define ESI_DLL_CFG_SLAVE_RDQS_DW1_F           0x8A6
#define ESI_DLL_CFG_SLAVE_RDQS_DW2_F           0x8A7
#define ESI_DLL_CFG_SLAVE_RDQS_DW3_F           0x8A8
#define ESI_DLL_CFG_SLAVE_RDQS_DW0_G           0x8C5
#define ESI_DLL_CFG_SLAVE_RDQS_DW1_G           0x8C6
#define ESI_DLL_CFG_SLAVE_RDQS_DW2_G           0x8C7
#define ESI_DLL_CFG_SLAVE_RDQS_DW3_G           0x8C8
#define ESI_DLL_CFG_SLAVE_RDQS_DW0_H           0x8E5
#define ESI_DLL_CFG_SLAVE_RDQS_DW1_H           0x8E6
#define ESI_DLL_CFG_SLAVE_RDQS_DW2_H           0x8E7
#define ESI_DLL_CFG_SLAVE_RDQS_DW3_H           0x8E8

#define ESI_TRAINING_PREFIX_IO_CFG            0x9
#define ESI_IO_CFG_AWORD_A                    0x900
#define ESI_IO_CFG_AWORD_B                    0x920
#define ESI_IO_CFG_AWORD_C                    0x940
#define ESI_IO_CFG_AWORD_D                    0x960
#define ESI_IO_CFG_AWORD_E                    0x980
#define ESI_IO_CFG_AWORD_F                    0x9A0
#define ESI_IO_CFG_AWORD_G                    0x9C0
#define ESI_IO_CFG_AWORD_H                    0x9E0
#define ESI_IO_CFG_DWORD_DW0_A                0x901
#define ESI_IO_CFG_DWORD_DW1_A                0x902
#define ESI_IO_CFG_DWORD_DW2_A                0x903
#define ESI_IO_CFG_DWORD_DW3_A                0x904
#define ESI_IO_CFG_DWORD_DW0_B                0x921
#define ESI_IO_CFG_DWORD_DW1_B                0x922
#define ESI_IO_CFG_DWORD_DW2_B                0x923
#define ESI_IO_CFG_DWORD_DW3_B                0x924
#define ESI_IO_CFG_DWORD_DW0_C                0x941
#define ESI_IO_CFG_DWORD_DW1_C                0x942
#define ESI_IO_CFG_DWORD_DW2_C                0x943
#define ESI_IO_CFG_DWORD_DW3_C                0x944
#define ESI_IO_CFG_DWORD_DW0_D                0x961
#define ESI_IO_CFG_DWORD_DW1_D                0x962
#define ESI_IO_CFG_DWORD_DW2_D                0x963
#define ESI_IO_CFG_DWORD_DW3_D                0x964
#define ESI_IO_CFG_DWORD_DW0_E                0x981
#define ESI_IO_CFG_DWORD_DW1_E                0x982
#define ESI_IO_CFG_DWORD_DW2_E                0x983
#define ESI_IO_CFG_DWORD_DW3_E                0x984
#define ESI_IO_CFG_DWORD_DW0_F                0x9A1
#define ESI_IO_CFG_DWORD_DW1_F                0x9A2
#define ESI_IO_CFG_DWORD_DW2_F                0x9A3
#define ESI_IO_CFG_DWORD_DW3_F                0x9A4
#define ESI_IO_CFG_DWORD_DW0_G                0x9C1
#define ESI_IO_CFG_DWORD_DW1_G                0x9C2
#define ESI_IO_CFG_DWORD_DW2_G                0x9C3
#define ESI_IO_CFG_DWORD_DW3_G                0x9C4
#define ESI_IO_CFG_DWORD_DW0_H                0x9E1
#define ESI_IO_CFG_DWORD_DW1_H                0x9E2
#define ESI_IO_CFG_DWORD_DW2_H                0x9E3
#define ESI_IO_CFG_DWORD_DW3_H                0x9E4

#define ESI_TRAINING_PREFIX_REPAIR            0xA
#define ESI_TRAINING_REPAIR_AW                0x00
#define ESI_REPAIR_AW_A                       0xA00
#define ESI_REPAIR_AW_B                       0xA20
#define ESI_REPAIR_AW_C                       0xA40
#define ESI_REPAIR_AW_D                       0xA60
#define ESI_REPAIR_AW_E                       0xA80
#define ESI_REPAIR_AW_F                       0xAA0
#define ESI_REPAIR_AW_G                       0xAC0
#define ESI_REPAIR_AW_H                       0xAE0
#define ESI_TRAINING_REPAIR_DW0                0x01
#define ESI_TRAINING_REPAIR_DW1                0x02
#define ESI_TRAINING_REPAIR_DW2                0x03
#define ESI_TRAINING_REPAIR_DW3                0x04
#define ESI_REPAIR_DW0_A                      0xA01
#define ESI_REPAIR_DW1_A                      0xA02
#define ESI_REPAIR_DW2_A                      0xA03
#define ESI_REPAIR_DW3_A                      0xA04
#define ESI_REPAIR_DW0_B                      0xA21
#define ESI_REPAIR_DW1_B                      0xA22
#define ESI_REPAIR_DW2_B                      0xA23
#define ESI_REPAIR_DW3_B                      0xA24
#define ESI_REPAIR_DW0_C                      0xA41
#define ESI_REPAIR_DW1_C                      0xA42
#define ESI_REPAIR_DW2_C                      0xA43
#define ESI_REPAIR_DW3_C                      0xA44
#define ESI_REPAIR_DW0_D                      0xA61
#define ESI_REPAIR_DW1_D                      0xA62
#define ESI_REPAIR_DW2_D                      0xA63
#define ESI_REPAIR_DW3_D                      0xA64
#define ESI_REPAIR_DW0_E                      0xA81
#define ESI_REPAIR_DW1_E                      0xA82
#define ESI_REPAIR_DW2_E                      0xA83
#define ESI_REPAIR_DW3_E                      0xA84
#define ESI_REPAIR_DW0_F                      0xAA1
#define ESI_REPAIR_DW1_F                      0xAA2
#define ESI_REPAIR_DW2_F                      0xAA3
#define ESI_REPAIR_DW3_F                      0xAA4
#define ESI_REPAIR_DW0_G                      0xAC1
#define ESI_REPAIR_DW1_G                      0xAC2
#define ESI_REPAIR_DW2_G                      0xAC3
#define ESI_REPAIR_DW3_G                      0xAC4
#define ESI_REPAIR_DW0_H                      0xAE1
#define ESI_REPAIR_DW1_H                      0xAE2
#define ESI_REPAIR_DW2_H                      0xAE3
#define ESI_REPAIR_DW3_H                      0xAE4

#define ESI_TRAINING_PREFIX_FIFORESET         0xB
#define ESI_TRAINING_FIFO_RESET_AW            0x00
#define ESI_TRAINING_FIFO_RESET_DW0           0x01
#define ESI_TRAINING_FIFO_RESET_DW1           0x02
#define ESI_TRAINING_FIFO_RESET_DW2           0x03
#define ESI_TRAINING_FIFO_RESET_DW3           0x04
#define ESI_FIFO_RESET_AW_A                   0xB00
#define ESI_FIFO_RESET_AW_B                   0xB20
#define ESI_FIFO_RESET_AW_C                   0xB40
#define ESI_FIFO_RESET_AW_D                   0xB60
#define ESI_FIFO_RESET_AW_E                   0xB80
#define ESI_FIFO_RESET_AW_F                   0xBA0
#define ESI_FIFO_RESET_AW_G                   0xBC0
#define ESI_FIFO_RESET_AW_H                   0xBE0
#define ESI_FIFO_RESET_DW0_A                  0xB01
#define ESI_FIFO_RESET_DW1_A                  0xB02
#define ESI_FIFO_RESET_DW2_A                  0xB03
#define ESI_FIFO_RESET_DW3_A                  0xB04
#define ESI_FIFO_RESET_DW0_B                  0xB21
#define ESI_FIFO_RESET_DW1_B                  0xB22
#define ESI_FIFO_RESET_DW2_B                  0xB23
#define ESI_FIFO_RESET_DW3_B                  0xB24
#define ESI_FIFO_RESET_DW0_C                  0xB41
#define ESI_FIFO_RESET_DW1_C                  0xB42
#define ESI_FIFO_RESET_DW2_C                  0xB43
#define ESI_FIFO_RESET_DW3_C                  0xB44
#define ESI_FIFO_RESET_DW0_D                  0xB61
#define ESI_FIFO_RESET_DW1_D                  0xB62
#define ESI_FIFO_RESET_DW2_D                  0xB63
#define ESI_FIFO_RESET_DW3_D                  0xB64
#define ESI_FIFO_RESET_DW0_E                  0xB81
#define ESI_FIFO_RESET_DW1_E                  0xB82
#define ESI_FIFO_RESET_DW2_E                  0xB83
#define ESI_FIFO_RESET_DW3_E                  0xB84
#define ESI_FIFO_RESET_DW0_F                  0xBA1
#define ESI_FIFO_RESET_DW1_F                  0xBA2
#define ESI_FIFO_RESET_DW2_F                  0xBA3
#define ESI_FIFO_RESET_DW3_F                  0xBA4
#define ESI_FIFO_RESET_DW0_G                  0xBC1
#define ESI_FIFO_RESET_DW1_G                  0xBC2
#define ESI_FIFO_RESET_DW2_G                  0xBC3
#define ESI_FIFO_RESET_DW3_G                  0xBC4
#define ESI_FIFO_RESET_DW0_H                  0xBE1
#define ESI_FIFO_RESET_DW1_H                  0xBE2
#define ESI_FIFO_RESET_DW2_H                  0xBE3
#define ESI_FIFO_RESET_DW3_H                  0xBE4


#define ESI_TRAINING_PREFIX_DLY_CFG             0xC
#define ESI_TRAINING_RDDLY_CFG_DW0              0x00
#define ESI_TRAINING_RDDLY_CFG_DW1              0x01
#define ESI_TRAINING_RDDLY_CFG_DW2              0x02
#define ESI_TRAINING_RDDLY_CFG_DW3              0x03
#define ESI_READ_DLY_CFG_DW0_A                0xC00
#define ESI_READ_DLY_CFG_DW1_A                0xC01
#define ESI_READ_DLY_CFG_DW2_A                0xC02
#define ESI_READ_DLY_CFG_DW3_A                0xC03
#define ESI_READ_DLY_CFG_DW0_B                0xC20
#define ESI_READ_DLY_CFG_DW1_B                0xC21
#define ESI_READ_DLY_CFG_DW2_B                0xC22
#define ESI_READ_DLY_CFG_DW3_B                0xC23
#define ESI_READ_DLY_CFG_DW0_C                0xC40
#define ESI_READ_DLY_CFG_DW1_C                0xC41
#define ESI_READ_DLY_CFG_DW2_C                0xC42
#define ESI_READ_DLY_CFG_DW3_C                0xC43
#define ESI_READ_DLY_CFG_DW0_D                0xC60
#define ESI_READ_DLY_CFG_DW1_D                0xC61
#define ESI_READ_DLY_CFG_DW2_D                0xC62
#define ESI_READ_DLY_CFG_DW3_D                0xC63
#define ESI_READ_DLY_CFG_DW0_E                0xC80
#define ESI_READ_DLY_CFG_DW1_E                0xC81
#define ESI_READ_DLY_CFG_DW2_E                0xC82
#define ESI_READ_DLY_CFG_DW3_E                0xC83
#define ESI_READ_DLY_CFG_DW0_F                0xCA0
#define ESI_READ_DLY_CFG_DW1_F                0xCA1
#define ESI_READ_DLY_CFG_DW2_F                0xCA2
#define ESI_READ_DLY_CFG_DW3_F                0xCA3
#define ESI_READ_DLY_CFG_DW0_G                0xCC0
#define ESI_READ_DLY_CFG_DW1_G                0xCC1
#define ESI_READ_DLY_CFG_DW2_G                0xCC2
#define ESI_READ_DLY_CFG_DW3_G                0xCC3
#define ESI_READ_DLY_CFG_DW0_H                0xCE0
#define ESI_READ_DLY_CFG_DW1_H                0xCE1
#define ESI_READ_DLY_CFG_DW2_H                0xCE2
#define ESI_READ_DLY_CFG_DW3_H                0xCE3

#define ESI_PARITY_LATENCY_A                  0xC04
#define ESI_PARITY_LATENCY_B                  0xC24
#define ESI_PARITY_LATENCY_C                  0xC44
#define ESI_PARITY_LATENCY_D                  0xC64
#define ESI_PARITY_LATENCY_E                  0xC84
#define ESI_PARITY_LATENCY_F                  0xCA4
#define ESI_PARITY_LATENCY_G                  0xCC4
#define ESI_PARITY_LATENCY_H                  0xCE4


#define ESI_TRAINING_PREFIX_AWMAN_CFG           0xD
#define ESI_TRAINING_AW_MAN_CFG_CK_CKE        0x00
#define ESI_AW_MAN_CFG_CK_CKE_A               0xD00
#define ESI_AW_MAN_CFG_CK_CKE_B               0xD20
#define ESI_AW_MAN_CFG_CK_CKE_C               0xD40
#define ESI_AW_MAN_CFG_CK_CKE_D               0xD60
#define ESI_AW_MAN_CFG_CK_CKE_E               0xD80
#define ESI_AW_MAN_CFG_CK_CKE_F               0xDA0
#define ESI_AW_MAN_CFG_CK_CKE_G               0xDC0
#define ESI_AW_MAN_CFG_CK_CKE_H               0xDE0
#define ESI_TRAINING_AW_MAN_CFG_ROW           0x01
#define ESI_AW_MAN_CFG_ROW_A                  0xD01
#define ESI_AW_MAN_CFG_ROW_B                  0xD21
#define ESI_AW_MAN_CFG_ROW_C                  0xD41
#define ESI_AW_MAN_CFG_ROW_D                  0xD61
#define ESI_AW_MAN_CFG_ROW_E                  0xD81
#define ESI_AW_MAN_CFG_ROW_F                  0xDA1
#define ESI_AW_MAN_CFG_ROW_G                  0xDC1
#define ESI_AW_MAN_CFG_ROW_H                  0xDE1
#define ESI_TRAINING_AW_MAN_CFG_COL           0x02
#define ESI_AW_MAN_CFG_COL_A                  0xD02
#define ESI_AW_MAN_CFG_COL_B                  0xD22
#define ESI_AW_MAN_CFG_COL_C                  0xD42
#define ESI_AW_MAN_CFG_COL_D                  0xD62
#define ESI_AW_MAN_CFG_COL_E                  0xD82
#define ESI_AW_MAN_CFG_COL_F                  0xDA2
#define ESI_AW_MAN_CFG_COL_G                  0xDC2
#define ESI_AW_MAN_CFG_COL_H                  0xDE2

#define ESI_AWORD_CLK_DISABLE                 0xD0F
#define ESI_DWORD_CLK_DISABLE                 0xD4F
#define ESI_AWORD_CLK_MC_DISABLE              0xD8F
#define ESI_DWORD_CLK_MC_DISABLE              0xDCF

#define ESI_AWORD_CLK_DISABLE_ABEF            0xD0F
#define ESI_DWORD_CLK_DISABLE_ABEF            0xD2F
#define ESI_AWORD_CLK_DISABLE_CDGH            0xD4F
#define ESI_DWORD_CLK_DISABLE_CDGH            0xD6F
#define ESI_AWORD_CLK_MC_DISABLE_ABEF         0xD8F
#define ESI_DWORD_CLK_MC_DISABLE_ABEF         0xDAF
#define ESI_AWORD_CLK_MC_DISABLE_CDGH         0xDCF
#define ESI_DWORD_CLK_MC_DISABLE_CDGH         0xDEF


#define ESI_TRAINING_PREFIX_MISRLB_CFG         0xE
#define ESI_TRAINING_MISRLB_CFG_DW0            0x07
#define ESI_TRAINING_MISRLB_CFG_DW1            0x0D
#define ESI_TRAINING_MISRLB_CFG_DW2            0x13
#define ESI_TRAINING_MISRLB_CFG_DW3            0x19
#define ESI_MISRLB_CFG_RUNTIME_A_0           0xE00
#define ESI_MISRLB_CFG_RUNTIME_A_1           0xE01
#define ESI_MISRLB_CFG_RUNTIME_B_0           0xE20
#define ESI_MISRLB_CFG_RUNTIME_B_1           0xE21
#define ESI_MISRLB_CFG_RUNTIME_C_0           0xE40
#define ESI_MISRLB_CFG_RUNTIME_C_1           0xE41
#define ESI_MISRLB_CFG_RUNTIME_D_0           0xE60
#define ESI_MISRLB_CFG_RUNTIME_D_1           0xE61
#define ESI_MISRLB_CFG_RUNTIME_E_0           0xE80
#define ESI_MISRLB_CFG_RUNTIME_E_1           0xE81
#define ESI_MISRLB_CFG_RUNTIME_F_0           0xEA0
#define ESI_MISRLB_CFG_RUNTIME_F_1           0xEA1
#define ESI_MISRLB_CFG_RUNTIME_G_0           0xEC0
#define ESI_MISRLB_CFG_RUNTIME_G_1           0xEC1
#define ESI_MISRLB_CFG_RUNTIME_H_0           0xEE0
#define ESI_MISRLB_CFG_RUNTIME_H_1           0xEE1
#define ESI_MISRLB_CFG_AW_A                  0xE02
#define ESI_MISRLB_CFG_DLY_AW_A              0xE03
#define ESI_MISRLB_CFG_READ_DLY_AW_A         0xE04
#define ESI_MISRLB_CFG_ERRINJ_AW_A           0xE05
#define ESI_MISRLB_CFG_MASK_AW_A             0xE06
#define ESI_MISRLB_CFG_AW_B                  0xE22
#define ESI_MISRLB_CFG_DLY_AW_B              0xE23
#define ESI_MISRLB_CFG_READ_DLY_AW_B         0xE24
#define ESI_MISRLB_CFG_ERRINJ_AW_B           0xE25
#define ESI_MISRLB_CFG_MASK_AW_B             0xE26
#define ESI_MISRLB_CFG_AW_C                  0xE42
#define ESI_MISRLB_CFG_DLY_AW_C              0xE43
#define ESI_MISRLB_CFG_READ_DLY_AW_C         0xE44
#define ESI_MISRLB_CFG_ERRINJ_AW_C           0xE45
#define ESI_MISRLB_CFG_MASK_AW_C             0xE46
#define ESI_MISRLB_CFG_AW_D                  0xE62
#define ESI_MISRLB_CFG_DLY_AW_D              0xE63
#define ESI_MISRLB_CFG_READ_DLY_AW_D         0xE64
#define ESI_MISRLB_CFG_ERRINJ_AW_D           0xE65
#define ESI_MISRLB_CFG_MASK_AW_D             0xE66
#define ESI_MISRLB_CFG_AW_E                  0xE82
#define ESI_MISRLB_CFG_DLY_AW_E              0xE83
#define ESI_MISRLB_CFG_READ_DLY_AW_E         0xE84
#define ESI_MISRLB_CFG_ERRINJ_AW_E           0xE85
#define ESI_MISRLB_CFG_MASK_AW_E             0xE86
#define ESI_MISRLB_CFG_AW_F                  0xEA2
#define ESI_MISRLB_CFG_DLY_AW_F              0xEA3
#define ESI_MISRLB_CFG_READ_DLY_AW_F         0xEA4
#define ESI_MISRLB_CFG_ERRINJ_AW_F           0xEA5
#define ESI_MISRLB_CFG_MASK_AW_F             0xEA6
#define ESI_MISRLB_CFG_AW_G                  0xEC2
#define ESI_MISRLB_CFG_DLY_AW_G              0xEC3
#define ESI_MISRLB_CFG_READ_DLY_AW_G         0xEC4
#define ESI_MISRLB_CFG_ERRINJ_AW_G           0xEC5
#define ESI_MISRLB_CFG_MASK_AW_G             0xEC6
#define ESI_MISRLB_CFG_AW_H                  0xEE2
#define ESI_MISRLB_CFG_DLY_AW_H              0xEE3
#define ESI_MISRLB_CFG_READ_DLY_AW_H         0xEE4
#define ESI_MISRLB_CFG_ERRINJ_AW_H           0xEE5
#define ESI_MISRLB_CFG_MASK_AW_H             0xEE6
#define ESI_MISRLB_CFG_DW0_A                 0xE07
#define ESI_MISRLB_CFG_DLY_DW0_A             0xE08
#define ESI_MISRLB_CFG_ERRINJ_DW0_A_0        0xE09
#define ESI_MISRLB_CFG_ERRINJ_DW0_A_1        0xE0A
#define ESI_MISRLB_CFG_MASK_DW0_A_0          0xE0B
#define ESI_MISRLB_CFG_MASK_DW0_A_1          0xE0C
#define ESI_MISRLB_CFG_DW1_A                 0xE0D
#define ESI_MISRLB_CFG_DLY_DW1_A             0xE0E
#define ESI_MISRLB_CFG_ERRINJ_DW1_A_0        0xE0F
#define ESI_MISRLB_CFG_ERRINJ_DW1_A_1        0xE10
#define ESI_MISRLB_CFG_MASK_DW1_A_0          0xE11
#define ESI_MISRLB_CFG_MASK_DW1_A_1          0xE12
#define ESI_MISRLB_CFG_DW2_A                 0xE13
#define ESI_MISRLB_CFG_DLY_DW2_A             0xE14
#define ESI_MISRLB_CFG_ERRINJ_DW2_A_0        0xE15
#define ESI_MISRLB_CFG_ERRINJ_DW2_A_1        0xE16
#define ESI_MISRLB_CFG_MASK_DW2_A_0          0xE17
#define ESI_MISRLB_CFG_MASK_DW2_A_1          0xE18
#define ESI_MISRLB_CFG_DW3_A                 0xE19
#define ESI_MISRLB_CFG_DLY_DW3_A             0xE1A
#define ESI_MISRLB_CFG_ERRINJ_DW3_A_0        0xE1B
#define ESI_MISRLB_CFG_ERRINJ_DW3_A_1        0xE1C
#define ESI_MISRLB_CFG_MASK_DW3_A_0          0xE1D
#define ESI_MISRLB_CFG_MASK_DW3_A_1          0xE1E
#define ESI_MISRLB_CFG_DW0_B                 0xE27
#define ESI_MISRLB_CFG_DLY_DW0_B             0xE28
#define ESI_MISRLB_CFG_ERRINJ_DW0_B_0        0xE29
#define ESI_MISRLB_CFG_ERRINJ_DW0_B_1        0xE2A
#define ESI_MISRLB_CFG_MASK_DW0_B_0          0xE2B
#define ESI_MISRLB_CFG_MASK_DW0_B_1          0xE2C
#define ESI_MISRLB_CFG_DW1_B                 0xE2D
#define ESI_MISRLB_CFG_DLY_DW1_B             0xE2E
#define ESI_MISRLB_CFG_ERRINJ_DW1_B_0        0xE2F
#define ESI_MISRLB_CFG_ERRINJ_DW1_B_1        0xE30
#define ESI_MISRLB_CFG_MASK_DW1_B_0          0xE31
#define ESI_MISRLB_CFG_MASK_DW1_B_1          0xE32
#define ESI_MISRLB_CFG_DW2_B                 0xE33
#define ESI_MISRLB_CFG_DLY_DW2_B             0xE34
#define ESI_MISRLB_CFG_ERRINJ_DW2_B_0        0xE35
#define ESI_MISRLB_CFG_ERRINJ_DW2_B_1        0xE36
#define ESI_MISRLB_CFG_MASK_DW2_B_0          0xE37
#define ESI_MISRLB_CFG_MASK_DW2_B_1          0xE38
#define ESI_MISRLB_CFG_DW3_B                 0xE39
#define ESI_MISRLB_CFG_DLY_DW3_B             0xE3A
#define ESI_MISRLB_CFG_ERRINJ_DW3_B_0        0xE3B
#define ESI_MISRLB_CFG_ERRINJ_DW3_B_1        0xE3C
#define ESI_MISRLB_CFG_MASK_DW3_B_0          0xE3D
#define ESI_MISRLB_CFG_MASK_DW3_B_1          0xE3E
#define ESI_MISRLB_CFG_DW0_C                 0xE47
#define ESI_MISRLB_CFG_DLY_DW0_C             0xE48
#define ESI_MISRLB_CFG_ERRINJ_DW0_C_0        0xE49
#define ESI_MISRLB_CFG_ERRINJ_DW0_C_1        0xE4A
#define ESI_MISRLB_CFG_MASK_DW0_C_0          0xE4B
#define ESI_MISRLB_CFG_MASK_DW0_C_1          0xE4C
#define ESI_MISRLB_CFG_DW1_C                 0xE4D
#define ESI_MISRLB_CFG_DLY_DW1_C             0xE4E
#define ESI_MISRLB_CFG_ERRINJ_DW1_C_0        0xE4F
#define ESI_MISRLB_CFG_ERRINJ_DW1_C_1        0xE50
#define ESI_MISRLB_CFG_MASK_DW1_C_0          0xE51
#define ESI_MISRLB_CFG_MASK_DW1_C_1          0xE52
#define ESI_MISRLB_CFG_DW2_C                 0xE53
#define ESI_MISRLB_CFG_DLY_DW2_C             0xE54
#define ESI_MISRLB_CFG_ERRINJ_DW2_C_0        0xE55
#define ESI_MISRLB_CFG_ERRINJ_DW2_C_1        0xE56
#define ESI_MISRLB_CFG_MASK_DW2_C_0          0xE57
#define ESI_MISRLB_CFG_MASK_DW2_C_1          0xE58
#define ESI_MISRLB_CFG_DW3_C                 0xE59
#define ESI_MISRLB_CFG_DLY_DW3_C             0xE5A
#define ESI_MISRLB_CFG_ERRINJ_DW3_C_0        0xE5B
#define ESI_MISRLB_CFG_ERRINJ_DW3_C_1        0xE5C
#define ESI_MISRLB_CFG_MASK_DW3_C_0          0xE5D
#define ESI_MISRLB_CFG_MASK_DW3_C_1          0xE5E
#define ESI_MISRLB_CFG_DW0_D                 0xE67
#define ESI_MISRLB_CFG_DLY_DW0_D             0xE68
#define ESI_MISRLB_CFG_ERRINJ_DW0_D_0        0xE69
#define ESI_MISRLB_CFG_ERRINJ_DW0_D_1        0xE6A
#define ESI_MISRLB_CFG_MASK_DW0_D_0          0xE6B
#define ESI_MISRLB_CFG_MASK_DW0_D_1          0xE6C
#define ESI_MISRLB_CFG_DW1_D                 0xE6D
#define ESI_MISRLB_CFG_DLY_DW1_D             0xE6E
#define ESI_MISRLB_CFG_ERRINJ_DW1_D_0        0xE6F
#define ESI_MISRLB_CFG_ERRINJ_DW1_D_1        0xE70
#define ESI_MISRLB_CFG_MASK_DW1_D_0          0xE71
#define ESI_MISRLB_CFG_MASK_DW1_D_1          0xE72
#define ESI_MISRLB_CFG_DW2_D                 0xE73
#define ESI_MISRLB_CFG_DLY_DW2_D             0xE74
#define ESI_MISRLB_CFG_ERRINJ_DW2_D_0        0xE75
#define ESI_MISRLB_CFG_ERRINJ_DW2_D_1        0xE76
#define ESI_MISRLB_CFG_MASK_DW2_D_0          0xE77
#define ESI_MISRLB_CFG_MASK_DW2_D_1          0xE78
#define ESI_MISRLB_CFG_DW3_D                 0xE79
#define ESI_MISRLB_CFG_DLY_DW3_D             0xE7A
#define ESI_MISRLB_CFG_ERRINJ_DW3_D_0        0xE7B
#define ESI_MISRLB_CFG_ERRINJ_DW3_D_1        0xE7C
#define ESI_MISRLB_CFG_MASK_DW3_D_0          0xE7D
#define ESI_MISRLB_CFG_MASK_DW3_D_1          0xE7E
#define ESI_MISRLB_CFG_DW0_E                 0xE87
#define ESI_MISRLB_CFG_DLY_DW0_E             0xE88
#define ESI_MISRLB_CFG_ERRINJ_DW0_E_0        0xE89
#define ESI_MISRLB_CFG_ERRINJ_DW0_E_1        0xE8A
#define ESI_MISRLB_CFG_MASK_DW0_E_0          0xE8B
#define ESI_MISRLB_CFG_MASK_DW0_E_1          0xE8C
#define ESI_MISRLB_CFG_DW1_E                 0xE8D
#define ESI_MISRLB_CFG_DLY_DW1_E             0xE8E
#define ESI_MISRLB_CFG_ERRINJ_DW1_E_0        0xE8F
#define ESI_MISRLB_CFG_ERRINJ_DW1_E_1        0xE90
#define ESI_MISRLB_CFG_MASK_DW1_E_0          0xE91
#define ESI_MISRLB_CFG_MASK_DW1_E_1          0xE92
#define ESI_MISRLB_CFG_DW2_E                 0xE93
#define ESI_MISRLB_CFG_DLY_DW2_E             0xE94
#define ESI_MISRLB_CFG_ERRINJ_DW2_E_0        0xE95
#define ESI_MISRLB_CFG_ERRINJ_DW2_E_1        0xE96
#define ESI_MISRLB_CFG_MASK_DW2_E_0          0xE97
#define ESI_MISRLB_CFG_MASK_DW2_E_1          0xE98
#define ESI_MISRLB_CFG_DW3_E                 0xE99
#define ESI_MISRLB_CFG_DLY_DW3_E             0xE9A
#define ESI_MISRLB_CFG_ERRINJ_DW3_E_0        0xE9B
#define ESI_MISRLB_CFG_ERRINJ_DW3_E_1        0xE9C
#define ESI_MISRLB_CFG_MASK_DW3_E_0          0xE9D
#define ESI_MISRLB_CFG_MASK_DW3_E_1          0xE9E
#define ESI_MISRLB_CFG_DW0_F                 0xEA7
#define ESI_MISRLB_CFG_DLY_DW0_F             0xEA8
#define ESI_MISRLB_CFG_ERRINJ_DW0_F_0        0xEA9
#define ESI_MISRLB_CFG_ERRINJ_DW0_F_1        0xEAA
#define ESI_MISRLB_CFG_MASK_DW0_F_0          0xEAB
#define ESI_MISRLB_CFG_MASK_DW0_F_1          0xEAC
#define ESI_MISRLB_CFG_DW1_F                 0xEAD
#define ESI_MISRLB_CFG_DLY_DW1_F             0xEAE
#define ESI_MISRLB_CFG_ERRINJ_DW1_F_0        0xEAF
#define ESI_MISRLB_CFG_ERRINJ_DW1_F_1        0xEB0
#define ESI_MISRLB_CFG_MASK_DW1_F_0          0xEB1
#define ESI_MISRLB_CFG_MASK_DW1_F_1          0xEB2
#define ESI_MISRLB_CFG_DW2_F                 0xEB3
#define ESI_MISRLB_CFG_DLY_DW2_F             0xEB4
#define ESI_MISRLB_CFG_ERRINJ_DW2_F_0        0xEB5
#define ESI_MISRLB_CFG_ERRINJ_DW2_F_1        0xEB6
#define ESI_MISRLB_CFG_MASK_DW2_F_0          0xEB7
#define ESI_MISRLB_CFG_MASK_DW2_F_1          0xEB8
#define ESI_MISRLB_CFG_DW3_F                 0xEB9
#define ESI_MISRLB_CFG_DLY_DW3_F             0xEBA
#define ESI_MISRLB_CFG_ERRINJ_DW3_F_0        0xEBB
#define ESI_MISRLB_CFG_ERRINJ_DW3_F_1        0xEBC
#define ESI_MISRLB_CFG_MASK_DW3_F_0          0xEBD
#define ESI_MISRLB_CFG_MASK_DW3_F_1          0xEBE
#define ESI_MISRLB_CFG_DW0_G                 0xEC7
#define ESI_MISRLB_CFG_DLY_DW0_G             0xEC8
#define ESI_MISRLB_CFG_ERRINJ_DW0_G_0        0xEC9
#define ESI_MISRLB_CFG_ERRINJ_DW0_G_1        0xECA
#define ESI_MISRLB_CFG_MASK_DW0_G_0          0xECB
#define ESI_MISRLB_CFG_MASK_DW0_G_1          0xECC
#define ESI_MISRLB_CFG_DW1_G                 0xECD
#define ESI_MISRLB_CFG_DLY_DW1_G             0xECE
#define ESI_MISRLB_CFG_ERRINJ_DW1_G_0        0xECF
#define ESI_MISRLB_CFG_ERRINJ_DW1_G_1        0xED0
#define ESI_MISRLB_CFG_MASK_DW1_G_0          0xED1
#define ESI_MISRLB_CFG_MASK_DW1_G_1          0xED2
#define ESI_MISRLB_CFG_DW2_G                 0xED3
#define ESI_MISRLB_CFG_DLY_DW2_G             0xED4
#define ESI_MISRLB_CFG_ERRINJ_DW2_G_0        0xED5
#define ESI_MISRLB_CFG_ERRINJ_DW2_G_1        0xED6
#define ESI_MISRLB_CFG_MASK_DW2_G_0          0xED7
#define ESI_MISRLB_CFG_MASK_DW2_G_1          0xED8
#define ESI_MISRLB_CFG_DW3_G                 0xED9
#define ESI_MISRLB_CFG_DLY_DW3_G             0xEDA
#define ESI_MISRLB_CFG_ERRINJ_DW3_G_0        0xEDB
#define ESI_MISRLB_CFG_ERRINJ_DW3_G_1        0xEDC
#define ESI_MISRLB_CFG_MASK_DW3_G_0          0xEDD
#define ESI_MISRLB_CFG_MASK_DW3_G_1          0xEDE
#define ESI_MISRLB_CFG_DW0_H                 0xEE7
#define ESI_MISRLB_CFG_DLY_DW0_H             0xEE8
#define ESI_MISRLB_CFG_ERRINJ_DW0_H_0        0xEE9
#define ESI_MISRLB_CFG_ERRINJ_DW0_H_1        0xEEA
#define ESI_MISRLB_CFG_MASK_DW0_H_0          0xEEB
#define ESI_MISRLB_CFG_MASK_DW0_H_1          0xEEC
#define ESI_MISRLB_CFG_DW1_H                 0xEED
#define ESI_MISRLB_CFG_DLY_DW1_H             0xEEE
#define ESI_MISRLB_CFG_ERRINJ_DW1_H_0        0xEEF
#define ESI_MISRLB_CFG_ERRINJ_DW1_H_1        0xEF0
#define ESI_MISRLB_CFG_MASK_DW1_H_0          0xEF1
#define ESI_MISRLB_CFG_MASK_DW1_H_1          0xEF2
#define ESI_MISRLB_CFG_DW2_H                 0xEF3
#define ESI_MISRLB_CFG_DLY_DW2_H             0xEF4
#define ESI_MISRLB_CFG_ERRINJ_DW2_H_0        0xEF5
#define ESI_MISRLB_CFG_ERRINJ_DW2_H_1        0xEF6
#define ESI_MISRLB_CFG_MASK_DW2_H_0          0xEF7
#define ESI_MISRLB_CFG_MASK_DW2_H_1          0xEF8
#define ESI_MISRLB_CFG_DW3_H                 0xEF9
#define ESI_MISRLB_CFG_DLY_DW3_H             0xEFA
#define ESI_MISRLB_CFG_ERRINJ_DW3_H_0        0xEFB
#define ESI_MISRLB_CFG_ERRINJ_DW3_H_1        0xEFC
#define ESI_MISRLB_CFG_MASK_DW3_H_0          0xEFD
#define ESI_MISRLB_CFG_MASK_DW3_H_1          0xEFE

//start signal
#define ESI_TRAINING_MISRLB_CFG_MODE         0x1F
#define ESI_MISRLB_CFG_MODE_A                0xE1F
#define ESI_MISRLB_CFG_MODE_B                0xE3F
#define ESI_MISRLB_CFG_MODE_C                0xE5F  
#define ESI_MISRLB_CFG_MODE_D                0xE7F    
#define ESI_MISRLB_CFG_MODE_E                0xE9F      
#define ESI_MISRLB_CFG_MODE_F                0xEBF        
#define ESI_MISRLB_CFG_MODE_G                0xEDF          
#define ESI_MISRLB_CFG_MODE_H                0xEFF            

#define ESI_TRAINING_PREFIX_MISRLB_STS         0xF
#define ESI_TRAINING_MISRLB_STS_AW           0x00
#define ESI_TRAINING_MISRLB_STS_DW0_0        0x01
#define ESI_TRAINING_MISRLB_STS_DW0_1        0x02
#define ESI_TRAINING_MISRLB_STS_DW1_0        0x03
#define ESI_TRAINING_MISRLB_STS_DW1_1        0x04
#define ESI_TRAINING_MISRLB_STS_DW2_0        0x05
#define ESI_TRAINING_MISRLB_STS_DW2_1        0x06
#define ESI_TRAINING_MISRLB_STS_DW3_0        0x07
#define ESI_TRAINING_MISRLB_STS_DW3_1        0x08

#define ESI_MISRLB_STS_AW_A                   0xF00
#define ESI_MISRLB_STS_DW0_A_0                0xF01
#define ESI_MISRLB_STS_DW0_A_1                0xF02
#define ESI_MISRLB_STS_DW1_A_0                0xF03
#define ESI_MISRLB_STS_DW1_A_1                0xF04
#define ESI_MISRLB_STS_DW2_A_0                0xF05
#define ESI_MISRLB_STS_DW2_A_1                0xF06
#define ESI_MISRLB_STS_DW3_A_0                0xF07
#define ESI_MISRLB_STS_DW3_A_1                0xF08
#define ESI_MISRLB_STS_AW_B                   0xF20
#define ESI_MISRLB_STS_DW0_B_0                0xF21
#define ESI_MISRLB_STS_DW0_B_1                0xF22
#define ESI_MISRLB_STS_DW1_B_0                0xF23
#define ESI_MISRLB_STS_DW1_B_1                0xF24
#define ESI_MISRLB_STS_DW2_B_0                0xF25
#define ESI_MISRLB_STS_DW2_B_1                0xF26
#define ESI_MISRLB_STS_DW3_B_0                0xF27
#define ESI_MISRLB_STS_DW3_B_1                0xF28
#define ESI_MISRLB_STS_AW_C                   0xF40
#define ESI_MISRLB_STS_DW0_C_0                0xF41
#define ESI_MISRLB_STS_DW0_C_1                0xF42
#define ESI_MISRLB_STS_DW1_C_0                0xF43
#define ESI_MISRLB_STS_DW1_C_1                0xF44
#define ESI_MISRLB_STS_DW2_C_0                0xF45
#define ESI_MISRLB_STS_DW2_C_1                0xF46
#define ESI_MISRLB_STS_DW3_C_0                0xF47
#define ESI_MISRLB_STS_DW3_C_1                0xF48
#define ESI_MISRLB_STS_AW_D                   0xF60
#define ESI_MISRLB_STS_DW0_D_0                0xF61
#define ESI_MISRLB_STS_DW0_D_1                0xF62
#define ESI_MISRLB_STS_DW1_D_0                0xF63
#define ESI_MISRLB_STS_DW1_D_1                0xF64
#define ESI_MISRLB_STS_DW2_D_0                0xF65
#define ESI_MISRLB_STS_DW2_D_1                0xF66
#define ESI_MISRLB_STS_DW3_D_0                0xF67
#define ESI_MISRLB_STS_DW3_D_1                0xF68
#define ESI_MISRLB_STS_AW_E                   0xF80
#define ESI_MISRLB_STS_DW0_E_0                0xF81
#define ESI_MISRLB_STS_DW0_E_1                0xF82
#define ESI_MISRLB_STS_DW1_E_0                0xF83
#define ESI_MISRLB_STS_DW1_E_1                0xF84
#define ESI_MISRLB_STS_DW2_E_0                0xF85
#define ESI_MISRLB_STS_DW2_E_1                0xF86
#define ESI_MISRLB_STS_DW3_E_0                0xF87
#define ESI_MISRLB_STS_DW3_E_1                0xF88
#define ESI_MISRLB_STS_AW_F                   0xFA0
#define ESI_MISRLB_STS_DW0_F_0                0xFA1
#define ESI_MISRLB_STS_DW0_F_1                0xFA2
#define ESI_MISRLB_STS_DW1_F_0                0xFA3
#define ESI_MISRLB_STS_DW1_F_1                0xFA4
#define ESI_MISRLB_STS_DW2_F_0                0xFA5
#define ESI_MISRLB_STS_DW2_F_1                0xFA6
#define ESI_MISRLB_STS_DW3_F_0                0xFA7
#define ESI_MISRLB_STS_DW3_F_1                0xFA8
#define ESI_MISRLB_STS_AW_G                   0xFC0
#define ESI_MISRLB_STS_DW0_G_0                0xFC1
#define ESI_MISRLB_STS_DW0_G_1                0xFC2
#define ESI_MISRLB_STS_DW1_G_0                0xFC3
#define ESI_MISRLB_STS_DW1_G_1                0xFC4
#define ESI_MISRLB_STS_DW2_G_0                0xFC5
#define ESI_MISRLB_STS_DW2_G_1                0xFC6
#define ESI_MISRLB_STS_DW3_G_0                0xFC7
#define ESI_MISRLB_STS_DW3_G_1                0xFC8
#define ESI_MISRLB_STS_AW_H                   0xFE0
#define ESI_MISRLB_STS_DW0_H_0                0xFE1
#define ESI_MISRLB_STS_DW0_H_1                0xFE2
#define ESI_MISRLB_STS_DW1_H_0                0xFE3
#define ESI_MISRLB_STS_DW1_H_1                0xFE4
#define ESI_MISRLB_STS_DW2_H_0                0xFE5
#define ESI_MISRLB_STS_DW2_H_1                0xFE6
#define ESI_MISRLB_STS_DW3_H_0                0xFE7
#define ESI_MISRLB_STS_DW3_H_1                0xFE8

#define ESI_MISRLB_ERR_PATTERN_AW_A_0         0xF09
#define ESI_MISRLB_ERR_PATTERN_AW_A_1         0xF0A
#define ESI_MISRLB_ERR_PATTERN_DW0_A_0        0xF0B
#define ESI_MISRLB_ERR_PATTERN_DW0_A_1        0xF0C
#define ESI_MISRLB_ERR_PATTERN_DW0_A_2        0xF0D
#define ESI_MISRLB_ERR_PATTERN_DW1_A_0        0xF0E
#define ESI_MISRLB_ERR_PATTERN_DW1_A_1        0xF0F
#define ESI_MISRLB_ERR_PATTERN_DW1_A_2        0xF10
#define ESI_MISRLB_ERR_PATTERN_DW2_A_0        0xF11
#define ESI_MISRLB_ERR_PATTERN_DW2_A_1        0xF12
#define ESI_MISRLB_ERR_PATTERN_DW2_A_2        0xF13
#define ESI_MISRLB_ERR_PATTERN_DW3_A_0        0xF14
#define ESI_MISRLB_ERR_PATTERN_DW3_A_1        0xF15
#define ESI_MISRLB_ERR_PATTERN_DW3_A_2        0xF16
#define ESI_MISRLB_ERR_PATTERN_AW_B_0         0xF29
#define ESI_MISRLB_ERR_PATTERN_AW_B_1         0xF2A
#define ESI_MISRLB_ERR_PATTERN_DW0_B_0        0xF2B
#define ESI_MISRLB_ERR_PATTERN_DW0_B_1        0xF2C
#define ESI_MISRLB_ERR_PATTERN_DW0_B_2        0xF2D
#define ESI_MISRLB_ERR_PATTERN_DW1_B_0        0xF2E
#define ESI_MISRLB_ERR_PATTERN_DW1_B_1        0xF2F
#define ESI_MISRLB_ERR_PATTERN_DW1_B_2        0xF30
#define ESI_MISRLB_ERR_PATTERN_DW2_B_0        0xF31
#define ESI_MISRLB_ERR_PATTERN_DW2_B_1        0xF32
#define ESI_MISRLB_ERR_PATTERN_DW2_B_2        0xF33
#define ESI_MISRLB_ERR_PATTERN_DW3_B_0        0xF34
#define ESI_MISRLB_ERR_PATTERN_DW3_B_1        0xF35
#define ESI_MISRLB_ERR_PATTERN_DW3_B_2        0xF36
#define ESI_MISRLB_ERR_PATTERN_AW_C_0         0xF49
#define ESI_MISRLB_ERR_PATTERN_AW_C_1         0xF4A
#define ESI_MISRLB_ERR_PATTERN_DW0_C_0        0xF4B
#define ESI_MISRLB_ERR_PATTERN_DW0_C_1        0xF4C
#define ESI_MISRLB_ERR_PATTERN_DW0_C_2        0xF4D
#define ESI_MISRLB_ERR_PATTERN_DW1_C_0        0xF4E
#define ESI_MISRLB_ERR_PATTERN_DW1_C_1        0xF4F
#define ESI_MISRLB_ERR_PATTERN_DW1_C_2        0xF50
#define ESI_MISRLB_ERR_PATTERN_DW2_C_0        0xF51
#define ESI_MISRLB_ERR_PATTERN_DW2_C_1        0xF52
#define ESI_MISRLB_ERR_PATTERN_DW2_C_2        0xF53
#define ESI_MISRLB_ERR_PATTERN_DW3_C_0        0xF54
#define ESI_MISRLB_ERR_PATTERN_DW3_C_1        0xF55
#define ESI_MISRLB_ERR_PATTERN_DW3_C_2        0xF56
#define ESI_MISRLB_ERR_PATTERN_AW_D_0         0xF69
#define ESI_MISRLB_ERR_PATTERN_AW_D_1         0xF6A
#define ESI_MISRLB_ERR_PATTERN_DW0_D_0        0xF6B
#define ESI_MISRLB_ERR_PATTERN_DW0_D_1        0xF6C
#define ESI_MISRLB_ERR_PATTERN_DW0_D_2        0xF6D
#define ESI_MISRLB_ERR_PATTERN_DW1_D_0        0xF6E
#define ESI_MISRLB_ERR_PATTERN_DW1_D_1        0xF6F
#define ESI_MISRLB_ERR_PATTERN_DW1_D_2        0xF70
#define ESI_MISRLB_ERR_PATTERN_DW2_D_0        0xF71
#define ESI_MISRLB_ERR_PATTERN_DW2_D_1        0xF72
#define ESI_MISRLB_ERR_PATTERN_DW2_D_2        0xF73
#define ESI_MISRLB_ERR_PATTERN_DW3_D_0        0xF74
#define ESI_MISRLB_ERR_PATTERN_DW3_D_1        0xF75
#define ESI_MISRLB_ERR_PATTERN_DW3_D_2        0xF76
#define ESI_MISRLB_ERR_PATTERN_AW_E_0         0xF89
#define ESI_MISRLB_ERR_PATTERN_AW_E_1         0xF8A
#define ESI_MISRLB_ERR_PATTERN_DW0_E_0        0xF8B
#define ESI_MISRLB_ERR_PATTERN_DW0_E_1        0xF8C
#define ESI_MISRLB_ERR_PATTERN_DW0_E_2        0xF8D
#define ESI_MISRLB_ERR_PATTERN_DW1_E_0        0xF8E
#define ESI_MISRLB_ERR_PATTERN_DW1_E_1        0xF8F
#define ESI_MISRLB_ERR_PATTERN_DW1_E_2        0xF90
#define ESI_MISRLB_ERR_PATTERN_DW2_E_0        0xF91
#define ESI_MISRLB_ERR_PATTERN_DW2_E_1        0xF92
#define ESI_MISRLB_ERR_PATTERN_DW2_E_2        0xF93
#define ESI_MISRLB_ERR_PATTERN_DW3_E_0        0xF94
#define ESI_MISRLB_ERR_PATTERN_DW3_E_1        0xF95
#define ESI_MISRLB_ERR_PATTERN_DW3_E_2        0xF96
#define ESI_MISRLB_ERR_PATTERN_AW_F_0         0xFA9
#define ESI_MISRLB_ERR_PATTERN_AW_F_1         0xFAA
#define ESI_MISRLB_ERR_PATTERN_DW0_F_0        0xFAB
#define ESI_MISRLB_ERR_PATTERN_DW0_F_1        0xFAC
#define ESI_MISRLB_ERR_PATTERN_DW0_F_2        0xFAD
#define ESI_MISRLB_ERR_PATTERN_DW1_F_0        0xFAE
#define ESI_MISRLB_ERR_PATTERN_DW1_F_1        0xFAF
#define ESI_MISRLB_ERR_PATTERN_DW1_F_2        0xFB0
#define ESI_MISRLB_ERR_PATTERN_DW2_F_0        0xFB1
#define ESI_MISRLB_ERR_PATTERN_DW2_F_1        0xFB2
#define ESI_MISRLB_ERR_PATTERN_DW2_F_2        0xFB3
#define ESI_MISRLB_ERR_PATTERN_DW3_F_0        0xFB4
#define ESI_MISRLB_ERR_PATTERN_DW3_F_1        0xFB5
#define ESI_MISRLB_ERR_PATTERN_DW3_F_2        0xFB6
#define ESI_MISRLB_ERR_PATTERN_AW_G_0         0xFC9
#define ESI_MISRLB_ERR_PATTERN_AW_G_1         0xFCA
#define ESI_MISRLB_ERR_PATTERN_DW0_G_0        0xFCB
#define ESI_MISRLB_ERR_PATTERN_DW0_G_1        0xFCC
#define ESI_MISRLB_ERR_PATTERN_DW0_G_2        0xFCD
#define ESI_MISRLB_ERR_PATTERN_DW1_G_0        0xFCE
#define ESI_MISRLB_ERR_PATTERN_DW1_G_1        0xFCF
#define ESI_MISRLB_ERR_PATTERN_DW1_G_2        0xFD0
#define ESI_MISRLB_ERR_PATTERN_DW2_G_0        0xFD1
#define ESI_MISRLB_ERR_PATTERN_DW2_G_1        0xFD2
#define ESI_MISRLB_ERR_PATTERN_DW2_G_2        0xFD3
#define ESI_MISRLB_ERR_PATTERN_DW3_G_0        0xFD4
#define ESI_MISRLB_ERR_PATTERN_DW3_G_1        0xFD5
#define ESI_MISRLB_ERR_PATTERN_DW3_G_2        0xFD6
#define ESI_MISRLB_ERR_PATTERN_AW_H_0         0xFE9
#define ESI_MISRLB_ERR_PATTERN_AW_H_1         0xFEA
#define ESI_MISRLB_ERR_PATTERN_DW0_H_0        0xFEB
#define ESI_MISRLB_ERR_PATTERN_DW0_H_1        0xFEC
#define ESI_MISRLB_ERR_PATTERN_DW0_H_2        0xFED
#define ESI_MISRLB_ERR_PATTERN_DW1_H_0        0xFEE
#define ESI_MISRLB_ERR_PATTERN_DW1_H_1        0xFEF
#define ESI_MISRLB_ERR_PATTERN_DW1_H_2        0xFF0
#define ESI_MISRLB_ERR_PATTERN_DW2_H_0        0xFF1
#define ESI_MISRLB_ERR_PATTERN_DW2_H_1        0xFF2
#define ESI_MISRLB_ERR_PATTERN_DW2_H_2        0xFF3
#define ESI_MISRLB_ERR_PATTERN_DW3_H_0        0xFF4
#define ESI_MISRLB_ERR_PATTERN_DW3_H_1        0xFF5
#define ESI_MISRLB_ERR_PATTERN_DW3_H_2        0xFF6


#define ESI_PHY_DBG_COUNTER_A                 0xF1F
#define ESI_PHY_DBG_COUNTER_B                 0xF3F
#define ESI_PHY_DBG_COUNTER_C                 0xF5F
#define ESI_PHY_DBG_COUNTER_D                 0xF7F
#define ESI_PHY_DBG_COUNTER_E                 0xF9F
#define ESI_PHY_DBG_COUNTER_F                 0xFBF
#define ESI_PHY_DBG_COUNTER_G                 0xFDF
#define ESI_PHY_DBG_COUNTER_H                 0xFFF


//training
#define ESI_MISR_DRAM_AWORD         0x0000
#define ESI_MISR_DRAM_WDQS          0x1
#define ESI_MISR_DRAM_RDQS          0x2
#define ESI_MISR_DRAM_DOREPAIR      0x3
#define ESI_MISR_DRAM_RDHARDREPAIR  0x4
#define ESI_MISR_DRAM_MRS_CFG       0x5
#define ESI_MISR_DRAM_STICKY        0x6
#define ESI_MISR_DRAM_BYPASS_AW     0x7
#define ESI_MISR_DRAM_BYPASS_DW     0x8

#define ESI_TRAIN_TYPE_CK    0x00
#define ESI_TRAIN_TYPE_WDQS  0x1
#define ESI_TRAIN_TYPE_RDQS  0x2
#define ESI_TRAIN_TYPE_RDSEL 0x3

