// the following blocknames (with uid) are from: leaba/trunk/Moriah/ASIC/design/defines/pacific_auto_unit_id_defines.v
`define SCH0_UID                      {}
`define SCH1_UID                      {}
`define SCH2_UID                      {}
`define SCH3_UID                      {}
`define SCH4_UID                      {}
`define SCH5_UID                      {}
`define SCH6_UID                      {}
`define SCH7_UID                      {}
`define SCH8_UID                      {}
`define SCH9_UID                      {}
`define SCH10_UID                     {}
`define SCH11_UID                     {}

`define PDOQ0_UID                     {}
`define PDOQ1_UID                     {}
`define PDOQ2_UID                     {}
`define PDOQ3_UID                     {}
`define PDOQ4_UID                     {}
`define PDOQ5_UID                     {}

`define PDOQ_EMPD0_UID                  {}
`define PDOQ_EMPD1_UID                  {}
`define PDOQ_EMPD2_UID                  {}
`define PDOQ_EMPD3_UID                  {}
`define PDOQ_EMPD4_UID                  {}
`define PDOQ_EMPD5_UID                  {}
`define PDOQ_EMPD6_UID                  {}
`define PDOQ_EMPD7_UID                  {}
`define PDOQ_EMPD8_UID                  {}
`define PDOQ_EMPD9_UID                  {}
`define PDOQ_EMPD10_UID                 {}
`define PDOQ_EMPD11_UID                 {}
`define PDOQ_EMPD12_UID                 {}
`define PDOQ_EMPD13_UID                 {}
`define PDOQ_EMPD14_UID                 {}
`define PDOQ_EMPD15_UID                 {}

`define PDOQ_FDOQ0_UID          {}
`define PDOQ_FDOQ1_UID          {}
`define PDOQ_FDOQ2_UID          {}
`define PDOQ_FDOQ3_UID          {}
`define PDOQ_FDOQ4_UID          {}
`define PDOQ_FDOQ5_UID          {}

`define PDVOQ_EMPD0_UID                {}
`define PDVOQ_EMPD1_UID                {}
`define PDVOQ_EMPD2_UID                {}
`define PDVOQ_EMPD3_UID                {}
`define PDVOQ_EMPD4_UID                {}
`define PDVOQ_EMPD5_UID                {}
`define PDVOQ_EMPD6_UID                {}
`define PDVOQ_EMPD7_UID                {}
`define PDVOQ_EMPD8_UID                {}
`define PDVOQ_EMPD9_UID                {}
`define PDVOQ_EMPD10_UID               {}
`define PDVOQ_EMPD11_UID               {}
`define PDVOQ_EMPD12_UID               {}
`define PDVOQ_EMPD13_UID               {}
`define PDVOQ_EMPD14_UID               {}
`define PDVOQ_EMPD15_UID               {}

`define PDVOQ_SLICE0_UID       {}
`define PDVOQ_SLICE1_UID       {}
`define PDVOQ_SLICE2_UID       {}
`define PDVOQ_SLICE3_UID       {}
`define PDVOQ_SLICE4_UID       {}
`define PDVOQ_SLICE5_UID       {}

`define FILB_SLICE0_UID               {}
`define FILB_SLICE1_UID               {}
`define FILB_SLICE2_UID               {}
`define FILB_SLICE3_UID               {}
`define FILB_SLICE4_UID               {}
`define FILB_SLICE5_UID               {}

`define FLLB_SLICE0_UID         {}
`define FLLB_SLICE1_UID         {}
`define FLLB_SLICE2_UID         {}
`define FLLB_SLICE3_UID         {}
`define FLLB_SLICE4_UID         {}
`define FLLB_SLICE5_UID         {}

`define ICS_SLICE0_UID         {}
`define ICS_SLICE1_UID         {}
`define ICS_SLICE2_UID         {}
`define ICS_SLICE3_UID         {}
`define ICS_SLICE4_UID         {}
`define ICS_SLICE5_UID         {}

`define IDB2_TOP_UID                  {}
`define IDB1_TOP_UID                  {}
`define IDB0_TOP_UID                  {}

`define IDB2_RES_UID                  {}
`define IDB1_RES_UID                  {}
`define IDB0_RES_UID                  {}

`define NW_REORDER_BLOCK0_UID         {}
`define NW_REORDER_BLOCK1_UID         {}
`define NW_REORDER_BLOCK2_UID         {}
`define NW_REORDER_BLOCK3_UID         {}
`define NW_REORDER_BLOCK4_UID         {}
`define NW_REORDER_BLOCK5_UID         {}

`define PP_REORDER_SLICE0_UID         {}
`define PP_REORDER_SLICE1_UID         {}
`define PP_REORDER_SLICE2_UID         {}


`define CDB_TOP_UID    		          {}
`define CDB_CORE0_UID                 {}
`define CDB_CORE1_UID                 {}
`define CDB_CORE2_UID                 {}
`define CDB_CORE3_UID                 {}
`define CDB_CORE4_UID                 {}
`define CDB_CORE5_UID                 {}
`define CDB_CORE6_UID                 {}
`define CDB_CORE7_UID                 {}

`define SDB_ENC_UID                   {}
`define SDB_MAC_UID                   {}

`define RX_METER_BLOCK0_UID             {}
`define RX_METER_BLOCK1_UID             {}
`define RX_METER_BLOCK2_UID             {}
`define RX_METER_BLOCK3_UID             {}

`define RX_PDR_2_SLICES0_UID          {}
`define RX_PDR_2_SLICES1_UID          {}
`define RX_PDR_2_SLICES2_UID          {}

`define RX_PDR_SHARED0_UID             {}
`define RX_PDR_SHARED1_UID             {}

`define RXPP0_CDB_CACHE_UID           {}
`define RXPP1_CDB_CACHE_UID           {}
`define RXPP2_CDB_CACHE_UID           {}
`define RXPP3_CDB_CACHE_UID           {}
`define RXPP4_CDB_CACHE_UID           {}
`define RXPP5_CDB_CACHE_UID           {}

`define RXPP0_FWD_UID                 {}
`define RXPP1_FWD_UID                 {}
`define RXPP2_FWD_UID                 {}
`define RXPP3_FWD_UID                 {}
`define RXPP4_FWD_UID                 {}
`define RXPP5_FWD_UID                 {}

`define RXPP0_SNA_UID                 {}
`define RXPP1_SNA_UID                 {}
`define RXPP2_SNA_UID                 {}
`define RXPP3_SNA_UID                 {}
`define RXPP4_SNA_UID                 {}
`define RXPP5_SNA_UID                 {}

`define RXPP0_TERM_UID                {}
`define RXPP1_TERM_UID                {}
`define RXPP2_TERM_UID                {}
`define RXPP3_TERM_UID                {}
`define RXPP4_TERM_UID                {}
`define RXPP5_TERM_UID                {}

`define RXPP0_FI_ENG0_UID             {}
`define RXPP0_FI_ENG1_UID             {}
`define RXPP0_FI_ENG2_UID             {}
`define RXPP0_FI_ENG3_UID             {}
`define RXPP0_FI_ENG4_UID             {}
`define RXPP0_FI_ENG5_UID             {}
`define RXPP0_FI_ENG6_UID             {}
`define RXPP0_FI_ENG7_UID             {}
`define RXPP1_FI_ENG0_UID             {}
`define RXPP1_FI_ENG1_UID             {}
`define RXPP1_FI_ENG2_UID             {}
`define RXPP1_FI_ENG3_UID             {}
`define RXPP1_FI_ENG4_UID             {}
`define RXPP1_FI_ENG5_UID             {}
`define RXPP1_FI_ENG6_UID             {}
`define RXPP1_FI_ENG7_UID             {}
`define RXPP2_FI_ENG0_UID             {}
`define RXPP2_FI_ENG1_UID             {}
`define RXPP2_FI_ENG2_UID             {}
`define RXPP2_FI_ENG3_UID             {}
`define RXPP2_FI_ENG4_UID             {}
`define RXPP2_FI_ENG5_UID             {}
`define RXPP2_FI_ENG6_UID             {}
`define RXPP2_FI_ENG7_UID             {}
`define RXPP3_FI_ENG0_UID             {}
`define RXPP3_FI_ENG1_UID             {}
`define RXPP3_FI_ENG2_UID             {}
`define RXPP3_FI_ENG3_UID             {}
`define RXPP3_FI_ENG4_UID             {}
`define RXPP3_FI_ENG5_UID             {}
`define RXPP3_FI_ENG6_UID             {}
`define RXPP3_FI_ENG7_UID             {}
`define RXPP4_FI_ENG0_UID             {}
`define RXPP4_FI_ENG1_UID             {}
`define RXPP4_FI_ENG2_UID             {}
`define RXPP4_FI_ENG3_UID             {}
`define RXPP4_FI_ENG4_UID             {}
`define RXPP4_FI_ENG5_UID             {}
`define RXPP4_FI_ENG6_UID             {}
`define RXPP4_FI_ENG7_UID             {}
`define RXPP5_FI_ENG0_UID             {}
`define RXPP5_FI_ENG1_UID             {}
`define RXPP5_FI_ENG2_UID             {}
`define RXPP5_FI_ENG3_UID             {}
`define RXPP5_FI_ENG4_UID             {}
`define RXPP5_FI_ENG5_UID             {}
`define RXPP5_FI_ENG6_UID             {}
`define RXPP5_FI_ENG7_UID             {}

`define RXPP0_FI_STAGE_UID            {}
`define RXPP1_FI_STAGE_UID            {}
`define RXPP2_FI_STAGE_UID            {}
`define RXPP3_FI_STAGE_UID            {}
`define RXPP4_FI_STAGE_UID            {}
`define RXPP5_FI_STAGE_UID            {}

`define TX_CGM0_UID                    {}
`define TX_CGM1_UID                    {}
`define TX_CGM2_UID                    {}
`define TX_CGM3_UID                    {}
`define TX_CGM4_UID                    {}
`define TX_CGM5_UID                    {}

`define TX_PDR0_UID                    {}
`define TX_PDR1_UID                    {}
`define TX_PDR2_UID                    {}
`define TX_PDR3_UID                    {}
`define TX_PDR4_UID                    {}
`define TX_PDR5_UID                    {}

`define TXPP0_UID                     {}
`define TXPP1_UID                     {}
`define TXPP2_UID                     {}
`define TXPP3_UID                     {}
`define TXPP4_UID                     {}
`define TXPP5_UID                     {}

`define TXPP0_CLUSTER0_UID            {}
`define TXPP0_CLUSTER1_UID            {}
`define TXPP1_CLUSTER0_UID            {}
`define TXPP1_CLUSTER1_UID            {}
`define TXPP2_CLUSTER0_UID            {}
`define TXPP2_CLUSTER1_UID            {}
`define TXPP3_CLUSTER0_UID            {}
`define TXPP3_CLUSTER1_UID            {}
`define TXPP4_CLUSTER0_UID            {}
`define TXPP4_CLUSTER1_UID            {}
`define TXPP5_CLUSTER0_UID            {}
`define TXPP5_CLUSTER1_UID            {}

`define RXPP0_NPE0_UID                {}
`define RXPP0_NPE1_UID                {}
`define RXPP0_NPE2_UID                {}
`define RXPP0_NPE3_UID                {}
`define RXPP0_NPE4_UID                {}
`define RXPP0_NPE5_UID                {}
`define RXPP1_NPE0_UID                {}
`define RXPP1_NPE1_UID                {}
`define RXPP1_NPE2_UID                {}
`define RXPP1_NPE3_UID                {}
`define RXPP1_NPE4_UID                {}
`define RXPP1_NPE5_UID                {}
`define RXPP2_NPE0_UID                {}
`define RXPP2_NPE1_UID                {}
`define RXPP2_NPE2_UID                {}
`define RXPP2_NPE3_UID                {}
`define RXPP2_NPE4_UID                {}
`define RXPP2_NPE5_UID                {}
`define RXPP3_NPE0_UID                {}
`define RXPP3_NPE1_UID                {}
`define RXPP3_NPE2_UID                {}
`define RXPP3_NPE3_UID                {}
`define RXPP3_NPE4_UID                {}
`define RXPP3_NPE5_UID                {}
`define RXPP4_NPE0_UID                {}
`define RXPP4_NPE1_UID                {}
`define RXPP4_NPE2_UID                {}
`define RXPP4_NPE3_UID                {}
`define RXPP4_NPE4_UID                {}
`define RXPP4_NPE5_UID                {}
`define RXPP5_NPE0_UID                {}
`define RXPP5_NPE1_UID                {}
`define RXPP5_NPE2_UID                {}
`define RXPP5_NPE3_UID                {}
`define RXPP5_NPE4_UID                {}
`define RXPP5_NPE5_UID                {}

`define TXPP0_NPE0_UID                {}
`define TXPP0_NPE1_UID                {}
`define TXPP1_NPE0_UID                {}
`define TXPP1_NPE1_UID                {}
`define TXPP2_NPE0_UID                {}
`define TXPP2_NPE1_UID                {}
`define TXPP3_NPE0_UID                {}
`define TXPP3_NPE1_UID                {}
`define TXPP4_NPE0_UID                {}
`define TXPP4_NPE1_UID                {}
`define TXPP5_NPE0_UID                {}
`define TXPP5_NPE1_UID                {}

`define NPUH_NPE_UID                  {}

`define TS_MS0_UID                    {}
`define TS_MS1_UID                    {}
`define TS_MS2_UID                    {}
`define TS_MS3_UID                    {}
`define TS_MS4_UID                    {}
`define TS_MS5_UID                    {}

`define CSMS_UID                      {}

// counter access registers
`define COUNTERS_UID                  {}

`define COUNTERS_BANK_GROUP0_UID           {}
`define COUNTERS_BANK_GROUP1_UID           {}
`define COUNTERS_BANK_GROUP2_UID           {}
`define COUNTERS_BANK_GROUP3_UID           {}
`define COUNTERS_BANK_GROUP4_UID           {}
`define COUNTERS_BANK_GROUP5_UID           {}
`define COUNTERS_BANK_GROUP6_UID           {}
`define COUNTERS_BANK_GROUP7_UID           {}
`define COUNTERS_BANK_GROUP8_UID           {}
`define COUNTERS_BANK_GROUP9_UID           {}
`define COUNTERS_BANK_GROUP10_UID          {}
`define COUNTERS_BANK_GROUP11_UID          {}
`define COUNTERS_BANK_GROUP12_UID          {}
`define COUNTERS_BANK_GROUP13_UID          {}
`define COUNTERS_BANK_GROUP14_UID          {}
`define COUNTERS_BANK_GROUP15_UID          {}
`define COUNTERS_BANK_GROUP16_UID          {}
`define COUNTERS_BANK_GROUP17_UID          {}
`define COUNTERS_BANK_GROUP18_UID          {}
`define COUNTERS_BANK_GROUP19_UID          {}
`define COUNTERS_BANK_GROUP20_UID          {}
`define COUNTERS_BANK_GROUP21_UID          {}
`define COUNTERS_BANK_GROUP22_UID          {}
`define COUNTERS_BANK_GROUP23_UID          {}
`define COUNTERS_BANK_GROUP24_UID          {}
`define COUNTERS_BANK_GROUP25_UID          {}
`define COUNTERS_BANK_GROUP26_UID          {}
`define COUNTERS_BANK_GROUP27_UID          {}
`define COUNTERS_BANK_GROUP28_UID          {}
`define COUNTERS_BANK_GROUP29_UID          {}
`define COUNTERS_BANK_GROUP30_UID          {}
`define COUNTERS_BANK_GROUP31_UID          {}
`define COUNTERS_BANK_GROUP32_UID          {}
`define COUNTERS_BANK_GROUP33_UID          {}
`define COUNTERS_BANK_GROUP34_UID          {}
`define COUNTERS_BANK_GROUP35_UID          {}

`define IFG0_IFGB_UID                 {}
`define IFG0_MAC_POOL2_0_UID          {}
`define IFG0_MAC_POOL8_0_UID          {}
`define IFG0_MAC_POOL8_1_UID          {}
`define IFG0_SERDES_POOL_UID          {}
`define IFG1_IFGB_UID                 {}
`define IFG1_MAC_POOL2_0_UID          {}
`define IFG1_MAC_POOL8_0_UID          {}
`define IFG1_MAC_POOL8_1_UID          {}
`define IFG1_SERDES_POOL_UID          {}
`define IFG3_IFGB_UID                 {}
`define IFG3_MAC_POOL2_0_UID          {}
`define IFG3_MAC_POOL8_0_UID          {}
`define IFG3_MAC_POOL8_1_UID          {}
`define IFG3_SERDES_POOL_UID          {}
`define IFG2_IFGB_UID                 {}
`define IFG2_MAC_POOL2_0_UID          {}
`define IFG2_MAC_POOL8_0_UID          {}
`define IFG2_MAC_POOL8_1_UID          {}
`define IFG2_SERDES_POOL_UID          {}
`define IFG5_IFGB_UID                 {}
`define IFG5_MAC_POOL2_0_UID          {}
`define IFG5_MAC_POOL8_0_UID          {}
`define IFG5_MAC_POOL8_1_UID          {}
`define IFG5_SERDES_POOL_UID          {}
`define IFG4_IFGB_UID                 {}
`define IFG4_MAC_POOL2_0_UID          {}
`define IFG4_MAC_POOL8_0_UID          {}
`define IFG4_MAC_POOL8_1_UID          {}
`define IFG4_SERDES_POOL_UID          {}
`define IFG6_IFGB_UID                 {}
`define IFG6_MAC_POOL2_0_UID          {}
`define IFG6_MAC_POOL8_0_UID          {}
`define IFG6_MAC_POOL8_1_UID          {}
`define IFG6_SERDES_POOL_UID          {}
`define IFG7_IFGB_UID                 {}
`define IFG7_MAC_POOL2_0_UID          {}
`define IFG7_MAC_POOL8_0_UID          {}
`define IFG7_MAC_POOL8_1_UID          {}
`define IFG7_SERDES_POOL_UID          {}
`define IFG8_IFGB_UID                 {}
`define IFG8_MAC_POOL2_0_UID          {}
`define IFG8_MAC_POOL8_0_UID          {}
`define IFG8_MAC_POOL8_1_UID          {}
`define IFG8_SERDES_POOL_UID          {}
`define IFG9_IFGB_UID                 {}
`define IFG9_MAC_POOL2_0_UID          {}
`define IFG9_MAC_POOL8_0_UID          {}
`define IFG9_MAC_POOL8_1_UID          {}
`define IFG9_SERDES_POOL_UID          {}
`define IFGB_IFGB_UID                 {}
`define IFGB_MAC_POOL2_0_UID          {}
`define IFGB_MAC_POOL8_0_UID          {}
`define IFGB_MAC_POOL8_1_UID          {}
`define IFGB_SERDES_POOL_UID          {}
`define IFGA_IFGB_UID                 {}
`define IFGA_MAC_POOL2_0_UID          {}
`define IFGA_MAC_POOL8_0_UID          {}
`define IFGA_MAC_POOL8_1_UID          {}
`define IFGA_SERDES_POOL_UID          {}

`define FDLL0_UID                      {}
`define FDLL1_UID                      {}
`define FDLL2_UID                      {}
`define FDLL3_UID                      {}
`define FDLL4_UID                      {}
`define FDLL5_UID                      {}
`define FDLL6_UID                      {}
`define FDLL7_UID                      {}

`define MMU_HBM_CHNL_0_1_UID            {}
`define MMU_HBM_CHNL_2_3_UID            {}
`define MMU_HBM_CHNL_4_5_UID            {}
`define MMU_HBM_CHNL_6_7_UID            {}
`define MMU_HBM_CHNL_8_9_UID            {}
`define MMU_HBM_CHNL_10_11_UID          {}
`define MMU_HBM_CHNL_12_13_UID          {}
`define MMU_HBM_CHNL_14_15_UID          {}

`define SMS_QUAD0_UID                 {}
`define SMS_QUAD1_UID                 {}
`define SMS_QUAD2_UID                 {}
`define SMS_QUAD3_UID                 {}

`define DICS_UID                      {}
`define DVOQ_UID                      {}
`define FDLL_SHARED_MEM_UID           {}
`define FRM_UID                       {}
`define FTE_UID                       {}
`define HBMHI_UID                     {}
`define HBMLO_UID                     {}
`define HMC_CGM_UID                   {}
`define ICS_TOP_UID                   {}
`define MMU_BUFF_UID                  {}
`define MMU_UID                       {}
`define MRB_UID                       {}
`define NPUH_FI_UID                   {}
`define NPUH_UID                      {}
`define NW_REORDER_UID                {}
`define PDOQ_SHARED_MEM_UID           {}
`define PDVOQ_SHARED_MMA_UID          {}
`define PIER_UID                      {}
`define REASSEMBLY_UID                {}
`define RX_CGM_UID                    {}
`define RX_COUNTERS_UID               {}
`define RX_METER_UID                  {}
`define RX_PDR_UID                    {}
`define SCH_TOP_UID                   {}
`define SMS_MAIN_UID                  {}
`define TS_MON_UID                    {}
`define TX_CGM_TOP_UID                {}
